In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation, Dropout
from tensorflow.keras.optimizers import SGD, RMSprop, Adam, AdamW
from tensorflow.keras import regularizers, models, layers
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau
from sklearn.preprocessing import StandardScaler

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import optuna
import wandb
import gc
import cv2

import os
import sqlite3

2026-03-20 08:13:43.353960: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-03-20 08:13:43.354002: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-03-20 08:13:43.354843: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-03-20 08:13:43.360024: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [2]:
tf.keras.backend.clear_session()

gpus = tf.config.list_physical_devices('GPU')

if gpus:
    print("TensorFlow is using the GPU \n", gpus)
else:
    print("No GPU detected.")

TensorFlow is using the GPU
 [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

2026-03-20 08:13:50.069983: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2026-03-20 08:13:50.079917: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2026-03-20 08:13:50.085544: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355

In [3]:
import wandb 

from wandb.integration.keras import WandbMetricsLogger

wandb.require("core")
wandb.login()

wandb: WARNING `wandb.require('core')` is a no-op as it is now the default behavior.
wandb: Currently logged in as: emmdaz (emmdaz-zzz) to https://api.wandb.ai. Use `wandb login --relogin` to force relogin

True

In [4]:
import uproot
from variables_calculator import variables_calculator

file = "/tf/Higgs-Boson-LHC-Collision-Detector/sigfcc_350.root"

data = uproot.open(file)
tree = data["Delphes"]

higgs_b = variables_calculator.inv_m(file, "jet_1", "jet_2", flavor1 = 3, flavor2 = 5)
higgs_b = higgs_b[["pt_1", "pt_2", "eta_1", "eta_2", "phi_1", "phi_2", "event_1", "inv_m"]].copy()
higgs_b.columns = ["PRI_jet_leading_pt", "PRI_jet_subleading_pt", "PRI_jet_leading_eta", "PRI_jet_subleading_eta", "PRI_jet_leading_phi",
                  "PRI_jet_subleading_phi", "event_1", "DER_mass_jet_jet"]

PRI_jet_num = variables_calculator.PRI_jet_num(file)
PRI_jet_all = variables_calculator.PRI_jet_all_pt(file)
met = variables_calculator.met(file)

jets_data = pd.merge(PRI_jet_all, PRI_jet_num, on = "event_1")
jets_data = pd.merge(jets_data, met, on = "event_1")
jets_data = pd.merge(jets_data, higgs_b, on = "event_1")

jets_data["label"] = np.full(len(jets_data), 1)

muon_data = variables_calculator.inv_m(file, "muon", "muon")
electron_data = variables_calculator.inv_m(file, "electron", "electron")
lepton_data = pd.concat([muon_data, electron_data])

lepton_data = lepton_data[["event_1", "inv_m"]].copy()
lepton_data.columns = ["event_1", "DER_mass_lep"]

signal = pd.merge(jets_data, lepton_data, on = "event_1")
signal = signal.drop(columns = ["event_1"])

file = "/tf/Higgs-Boson-LHC-Collision-Detector/bgd240zh.root"

data = uproot.open(file)
tree = data["Delphes"]

higgs_b = variables_calculator.inv_m(file, "jet_1", "jet_2", flavor1 = 3, flavor2 = 5)
higgs_b = higgs_b[["pt_1", "pt_2", "eta_1", "eta_2", "phi_1", "phi_2", "event_1", "inv_m"]].copy()
higgs_b.columns = ["PRI_jet_leading_pt", "PRI_jet_subleading_pt", "PRI_jet_leading_eta", "PRI_jet_subleading_eta", "PRI_jet_leading_phi",
                  "PRI_jet_subleading_phi", "event_1", "DER_mass_jet_jet"]

PRI_jet_num = variables_calculator.PRI_jet_num(file)
PRI_jet_all = variables_calculator.PRI_jet_all_pt(file)
met = variables_calculator.met(file)

jets_data = pd.merge(PRI_jet_all, PRI_jet_num, on = "event_1")
jets_data = pd.merge(jets_data, met, on = "event_1")
jets_data = pd.merge(jets_data, higgs_b, on = "event_1")

jets_data["label"] = np.full(len(jets_data), 0)

muon_data = variables_calculator.inv_m(file, "muon", "muon")
electron_data = variables_calculator.inv_m(file, "electron", "electron")
lepton_data = pd.concat([muon_data, electron_data])

lepton_data = lepton_data[["event_1", "inv_m"]].copy()
lepton_data.columns = ["event_1", "DER_mass_lep"]

noise1 = pd.merge(jets_data, lepton_data, on = "event_1")
noise1 = noise1.drop(columns = ["event_1"])

# Noise 2
file = "/tf/Higgs-Boson-LHC-Collision-Detector/bgd365eez.root"

data = uproot.open(file)
tree = data["Delphes"]

higgs_b = variables_calculator.inv_m(file, "jet_1", "jet_2", flavor1 = 3, flavor2 = 5)
higgs_b = higgs_b[["pt_1", "pt_2", "eta_1", "eta_2", "phi_1", "phi_2", "event_1", "inv_m"]].copy()
higgs_b.columns = ["PRI_jet_leading_pt", "PRI_jet_subleading_pt", "PRI_jet_leading_eta", "PRI_jet_subleading_eta", "PRI_jet_leading_phi",
                  "PRI_jet_subleading_phi", "event_1", "DER_mass_jet_jet"]

PRI_jet_num = variables_calculator.PRI_jet_num(file)
PRI_jet_all = variables_calculator.PRI_jet_all_pt(file)
met = variables_calculator.met(file)

jets_data = pd.merge(PRI_jet_all, PRI_jet_num, on = "event_1")
jets_data = pd.merge(jets_data, met, on = "event_1")
jets_data = pd.merge(jets_data, higgs_b, on = "event_1")

jets_data["label"] = np.full(len(jets_data), 0)

muon_data = variables_calculator.inv_m(file, "muon", "muon")
electron_data = variables_calculator.inv_m(file, "electron", "electron")
lepton_data = pd.concat([muon_data, electron_data])

lepton_data = lepton_data[["event_1", "inv_m"]].copy()
lepton_data.columns = ["event_1", "DER_mass_lep"]

noise2 = pd.merge(jets_data, lepton_data, on = "event_1")
noise2 = noise2.drop(columns = ["event_1"])

noise = pd.concat([noise1, noise2])

bg_sample1 = noise.sample(frac = 0.5, random_state = 4)
bg_sample2 = noise.sample(frac = 0.3, random_state = 4)
bg_sample3 = noise.sample(frac = 0.2, random_state = 4)

sg_sample1 = signal.sample(n = len(bg_sample1)*3, random_state = 4)
sg_sample2 = signal.sample(n = len(bg_sample2)*3, random_state = 4)
sg_sample3 = signal.sample(n = len(bg_sample3)*3, random_state = 4)

train = pd.concat([sg_sample1, bg_sample1])
test = pd.concat([sg_sample2, bg_sample2])
val = pd.concat([sg_sample3, bg_sample3])

train = train.sample(frac = 1, random_state = 5).reset_index(drop = True)
test = test.sample(frac = 1, random_state = 5).reset_index(drop = True)
val = val.sample(frac = 1, random_state = 5).reset_index(drop = True)

# Now we can create the subsets:
X_train, X_test, X_val = train.drop(columns = ["label"]), test.drop(columns = ["label"]), val.drop(columns = ["label"])
y_train, y_test, y_val = train["label"], test["label"], val["label"]

# And we stardardize the data:

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_val = scaler.transform(X_val)
X_test = scaler.transform(X_test)

# Check the sizes
print("Train size:", len(X_train))
print("Validation size:", len(X_val))
print("Test size:", len(X_test))

Train size: 1700
Validation size: 680
Test size: 1020

/usr/local/lib/python3.11/dist-packages/pandas/core/arraylike.py:399: RuntimeWarning: invalid value encountered in sqrt
  result = getattr(ufunc, method)(*inputs, **kwargs)

In [5]:
print(len(sg_sample1))
print(len(bg_sample1))

1275
425

In [6]:
signal.head()

,PRI_jet_all_pt,PRI_jet_num,PRI_met,PRI_met_phi,PRI_jet_leading_pt,PRI_jet_subleading_pt,PRI_jet_leading_eta,PRI_jet_subleading_eta,PRI_jet_leading_phi,PRI_jet_subleading_phi,DER_mass_jet_jet,label,DER_mass_lep
0,170.760605,3,4.302101,-1.388696,64.256523,36.597229,-0.113773,-1.709504,2.964018,-1.596112,113.084663,1,85.018837
1,304.227875,3,4.129518,2.948901,39.575764,127.212677,-0.525154,0.348251,1.704656,-3.009968,118.901390,1,82.369003
2,283.492126,3,2.992920,1.142674,137.516327,11.906924,0.033779,-1.482367,-1.903679,-0.247148,89.987083,1,92.270065
3,242.444855,3,5.493720,-2.066545,41.898006,102.129112,0.853439,0.485302,2.301678,-1.990217,112.418762,1,83.204475
4,230.607391,3,2.175927,1.302745,63.231850,81.647446,1.091058,0.237706,-0.946260,0.968609,133.423233,1,83.884644

In [7]:
train.head()

,PRI_jet_all_pt,PRI_jet_num,PRI_met,PRI_met_phi,PRI_jet_leading_pt,PRI_jet_subleading_pt,PRI_jet_leading_eta,PRI_jet_subleading_eta,PRI_jet_leading_phi,PRI_jet_subleading_phi,DER_mass_jet_jet,label,DER_mass_lep
0,239.087677,3,2.918416,-1.136685,97.319443,39.325672,-0.874773,0.070722,1.735062,0.158167,106.700081,1,89.485268
1,143.534821,3,11.685090,0.848280,64.629486,65.953690,0.791193,-0.148890,-2.195308,0.958930,145.266388,0,89.182938
2,198.904312,3,21.869644,-1.976044,28.644110,87.506470,0.829670,0.687386,1.511135,-1.952377,99.093338,1,92.251511
3,261.334290,4,7.230958,-0.462780,100.688171,16.901278,-0.821157,1.183019,-0.490292,-0.689705,97.571991,1,92.205437
4,284.861328,3,6.746761,-0.707597,119.034531,44.812328,0.146229,0.849623,3.042453,-1.610380,118.546295,1,93.519783

In [8]:
# We define a function to create residual blocks (considering a layer regularizer L2)

def residual_block(x, n, activation, dropout, dropout_rate, regularizer, r_2):
        
    residual = x  
        
    if dropout == "y":
        # Main path
        x = layers.Dense(n, activation = activation, kernel_regularizer = regularizers.l2(r_2))(x)
        x = layers.BatchNormalization()(x)
        
        # Intermediate dropout layer
        x = layers.Dropout(dropout_rate)(x)
            
        # Linear layer
        x = layers.Dense(n, kernel_regularizer = regularizers.l2(r_2))(x)
        x = layers.BatchNormalization()(x)
            
    else: 
        # Main path
        x = layers.Dense(n, activation = activation, kernel_regularizer = regularizers.l2(r_2))(x)
        x = layers.BatchNormalization()(x)
            
        # Linear layer
        x = layers.Dense(n, kernel_regularizer = regularizers.l2(r_2))(x)
        x = layers.BatchNormalization()(x)

    # Project shortcut to same dimension
    residual = layers.Dense(n)(residual)

    # Conection residual sum
    x = layers.add([x, residual]) 
    x = layers.Activation(activation)(x)
        
    return x

In [9]:
# We create the function to start the study and optimizarion using Optuna
def objective(trial):

    tf.keras.backend.clear_session()

    inputs = layers.Input(shape = (X_train.shape[1],))
    
    #############################################################################################################
    
    # Optuna suggests activation function for all layers
    activation = trial.suggest_categorical("activation", ["relu", "relu6", "leaky_relu"])
    
    # Optuna suggests regularizer L2 value
    regularizer = "L2"
    r_2 = trial.suggest_float("regularizer_value_2", 1e-7, 1e-5, log = True)
    
    # Optuna suggest the number of layers
    n_layers = trial.suggest_int("N_layers", 15,20)
    
    # Optuna suggests learning rate value and an optimizer
    lr = trial.suggest_float("learning_rate", 2.5e-4, 1e-3, log = True)
    
    optimizer_name = trial.suggest_categorical("optimizer", ["sgd", "adam", "rmsprop", "adamw"])
                              
    if optimizer_name == "sgd":
        optimizer = tf.keras.optimizers.SGD(learning_rate = lr)
    elif optimizer_name == "adam":
        optimizer = tf.keras.optimizers.Adam(learning_rate = lr)
    elif optimizer_name == "rmsprop":
        optimizer = tf.keras.optimizers.RMSprop(learning_rate = lr)
    elif optimizer_name == "adamw":
        optimizer = tf.keras.optimizers.AdamW(learning_rate = lr)              
    
    #############################################################################################################
    
    # First layer

    # Optuna suggest number of neurons for the first layer

    N = trial.suggest_int("N_1st_layer", 128, 256)
    
    x = layers.Dense(N, input_shape = (X_train.shape[1],))(inputs)
    x = layers.Activation(activation)(x)
    x = layers.BatchNormalization()(x)
    
    # Optuna suggests neurons for the residual blocks and if using Dropout block
    
    dropout_per_layer = []
    dropout_percentage_per_layer = []
            
    dropping_out = trial.suggest_categorical("Dropout", ["y", "n"])

    N_per_layer = []
    
    for i in range(n_layers):
        
        n = trial.suggest_int(f"N_{i+1}_layer", 128, 256)
        N_per_layer.append(n)
                              
        dropout_rate = trial.suggest_float(f"Dropout_value_L{i+2}",0.1, 0.15)
        
        # i-th residual block:
        
        # Choosing between Dropout or a regulizer
        
        if dropping_out == "y":
            dropout_percentage_per_layer.append(dropout_rate)
            x = residual_block(x, n, activation, "y", dropout_rate, regularizer, r_2)

        else:
            dropout_percentage_per_layer.append(0.0)
            x = residual_block(x, n, activation, "n", dropout_rate, regularizer, r_2)            
            
    x = layers.Dropout(0.4)(x)  
    outputs = layers.Dense(1, activation = "sigmoid")(x)
    model = models.Model(inputs, outputs)
                              
    model.compile(optimizer = optimizer,
                  loss = "binary_crossentropy",
                  metrics = ["accuracy",
                             tf.keras.metrics.Precision(),
                             tf.keras.metrics.AUC(curve = "ROC"),
                             tf.keras.metrics.AUC(curve = "PR")])
    
    #############################################################################################################

    wandb.init(
        project = "Residual-SnB-Trials-HB-No-Balanced-1.0",
        name = f"Trial_{trial.number}",
        reinit = True,
        config = {
            "Units_1": N,
            "Units_per_layer": N_per_layer,
            "activation": activation,
            "n_layers": n_layers,
            "regularizer": regularizer,
            "r_value2": r_2,
            "Dropout": dropping_out, 
            "dropout_percentage_per_layer": dropout_percentage_per_layer,
            "learning_rate": lr,
            "optimizer": optimizer_name        }
    )
    
    #############################################################################################################
    
    """
    Callbacks
    """
    early_stopping = EarlyStopping(monitor = "val_accuracy", patience = 7, restore_best_weights = True)
    lr_reduction = ReduceLROnPlateau(monitor = "val_loss", factor = 0.1, patience = 5)
#     tensorboard_cb = TensorBoard(log_dir = "/workspace/Optuna-Trials/Plant-Pathology-Classificator/tf_debug", histogram_freq = 1, write_graph = True,
#                                  write_images = False)
    
    #############################################################################################################
    
    """
    Creación del modelo
    """
    
    try:
        print(model.summary())
    
        history = model.fit(
            X_train, y_train,
            validation_data = (X_test, y_test),
            batch_size = 32,
            epochs = 200,
            verbose = 1, 
            callbacks = [WandbMetricsLogger(log_freq = 5), early_stopping, lr_reduction]
        )

        val_loss = min(history.history["val_loss"])
        val_accuracy = max(history.history["val_accuracy"])
        
        train_loss = min(history.history["loss"])
        train_accuracy = max(history.history["accuracy"])
    
    except tf.errors.ResourceExhaustedError as e:
        
        print(f"Intento {trial.number} falló debido a: {e}")
        
        tf.keras.backend.clear_session()
        wandb.finish()
        gc.collect()
        
        return float("inf")

    except Exception as e:
        
        print(f"Intento {trial.number} falló. Unexpected error: {e}")
        
        tf.keras.backend.clear_session()
        wandb.finish()
        gc.collect()
        
        return float("inf")
    
    # score = val_loss + 0.1 * (train_loss - val_loss)
    
    score = val_accuracy
    
    # score = train_loss 
    
    tf.keras.backend.clear_session()
    gc.collect()
    wandb.finish()

    return 1-score

In [10]:
tf.keras.backend.clear_session()
gc.collect()

from tensorflow.keras import backend as K

K.clear_session()

In [ ]:
study = optuna.create_study(
    study_name = "Residual-Trials_HB(Balanced)-1.0",
    direction = "minimize",
    storage = "sqlite:////workspace/Optuna-Trials/ResNet_SnB(No-Balanced)_study.db",
    load_if_exists = True
)

study.optimize(objective, n_trials = 500, n_jobs = 1)

[I 2026-03-20 08:14:18,189] Using an existing study with name 'Residual-Trials_HB(Balanced)-1.0' instead of creating a new one.
2026-03-20 08:14:18.293251: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2026-03-20 08:14:18.296383: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2026-03-20 08:14:18.298636: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2026-03-20 08:14:18.429774: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2026-03-20 08:14:18.430582: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2026-03-20 08:14:18.431333: I external/local_xla/xla/stream_executor/cuda/cuda_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2026-03-20 08:14:18.432035: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1929] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 1520 MB memory:  -> device: 0, name: NVIDIA GeForce GTX 1650, pci bus id: 0000:01:00.0, compute capability: 7.5
wandb: WARNING Using a boolean value for 'reinit' is deprecated. Use 'return_previous' or 'finish_previous' instead.

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to
==================================================================================================
 input_1 (InputLayer)        [(None, 12)]                 0         []

 dense (Dense)               (None, 180)                  2340      ['input_1[0][0]']

 activation (Activation)     (None, 180)                  0         ['dense[0][0]']

 batch_normalization (Batch  (None, 180)                  720       ['activation[0][0]']
 Normalization)

 dense_1 (Dense)             (None, 255)                  46155     ['batch_normalization[0][0]']

 batch_normalization_1 (Bat  (None, 255)                  1020      ['dense_1[0][0]']
 chNormalization)

 dense_2 (Dense)             (None, 255)                  65280     ['batch_normalization_1[0][0]'
                                                                    ]

 batch_normalization_2 (Bat  (None, 255)                  1020      ['dense_2[0][0]']
 chNormalization)

 dense_3 (Dense)             (None, 255)                  46155     ['batch_normalization[0][0]']

 add (Add)                   (None, 255)                  0         ['batch_normalization_2[0][0]'
                                                                    , 'dense_3[0][0]']

 activation_1 (Activation)   (None, 255)                  0         ['add[0][0]']

 dense_4 (Dense)             (None, 220)                  56320     ['activation_1[0][0]']

 batch_normalization_3 (Bat  (None, 220)                  880       ['dense_4[0][0]']
 chNormalization)

 dense_5 (Dense)             (None, 220)                  48620     ['batch_normalization_3[0][0]'
                                                                    ]

 batch_normalization_4 (Bat  (None, 220)                  880       ['dense_5[0][0]']
 chNormalization)

 dense_6 (Dense)             (None, 220)                  56320     ['activation_1[0][0]']

 add_1 (Add)                 (None, 220)                  0         ['batch_normalization_4[0][0]'
                                                                    , 'dense_6[0][0]']

 activation_2 (Activation)   (None, 220)                  0         ['add_1[0][0]']

 dense_7 (Dense)             (None, 158)                  34918     ['activation_2[0][0]']

 batch_normalization_5 (Bat  (None, 158)                  632       ['dense_7[0][0]']
 chNormalization)

 dense_8 (Dense)             (None, 158)                  25122     ['batch_normalization_5[0][0]'
                                                                    ]

 batch_normalization_6 (Bat  (None, 158)                  632       ['dense_8[0][0]']
 chNormalization)

 dense_9 (Dense)             (None, 158)                  34918     ['activation_2[0][0]']

 add_2 (Add)                 (None, 158)                  0         ['batch_normalization_6[0][0]'
                                                                    , 'dense_9[0][0]']

 activation_3 (Activation)   (None, 158)                  0         ['add_2[0][0]']

 dense_10 (Dense)            (None, 165)                  26235     ['activation_3[0][0]']

 batch_normalization_7 (Bat  (None, 165)                  660       ['dense_10[0][0]']
 chNormalization)

 dense_11 (Dense)            (None, 165)                  27390     ['batch_normalization_7[0][0]'
                                                                    ]

 batch_normalization_8 (Bat  (None, 165)                  660       ['dense_11[0][0]']
 chNormalization)

 dense_12 (Dense)            (None, 165)                  26235     ['activation_3[0][0]']

 add_3 (Add)                 (None, 165)                  0         ['batch_normalization_8[0][0]'
                                                                    , 'dense_12[0][0]']

 activation_4 (Activation)   (None, 165)                  0         ['add_3[0][0]']

 dense_13 (Dense)            (None, 255)                  42330     ['activation_4[0][0]']

 batch_normalization_9 (Bat  (None, 255)                  1020      ['dense_13[0][0]']
 chNormalization)

 dense_14 (Dense)            (None, 255)                  65280     ['batch_normalization_9[0][0]'
                                                                    ]

 batch_normalization_10 (Ba  (None, 255)                  1020      ['dense_14[0][0]']
 tchNormalization)

 dense_15 (Dense)            (None, 255)                  42330     ['activation_4[0][0]']

 add_4 (Add)                 (None, 255)                  0         ['batch_normalization_10[0][0]
                                                                    ',
                                                                     'dense_15[0][0]']

 activation_5 (Activation)   (None, 255)                  0         ['add_4[0][0]']

 dense_16 (Dense)            (None, 190)                  48640     ['activation_5[0][0]']

 batch_normalization_11 (Ba  (None, 190)                  760       ['dense_16[0][0]']
 tchNormalization)

 dense_17 (Dense)            (None, 190)                  36290     ['batch_normalization_11[0][0]
                                                                    ']

 batch_normalization_12 (Ba  (None, 190)                  760       ['dense_17[0][0]']
 tchNormalization)

 dense_18 (Dense)            (None, 190)                  48640     ['activation_5[0][0]']

 add_5 (Add)                 (None, 190)                  0         ['batch_normalization_12[0][0]
                                                                    ',
                                                                     'dense_18[0][0]']

 activation_6 (Activation)   (None, 190)                  0         ['add_5[0][0]']

 dense_19 (Dense)            (None, 128)                  24448     ['activation_6[0][0]']

 batch_normalization_13 (Ba  (None, 128)                  512       ['dense_19[0][0]']
 tchNormalization)

 dense_20 (Dense)            (None, 128)                  16512     ['batch_normalization_13[0][0]
                                                                    ']

 batch_normalization_14 (Ba  (None, 128)                  512       ['dense_20[0][0]']
 tchNormalization)

 dense_21 (Dense)            (None, 128)                  24448     ['activation_6[0][0]']

 add_6 (Add)                 (None, 128)                  0         ['batch_normalization_14[0][0]
                                                                    ',
                                                                     'dense_21[0][0]']

 activation_7 (Activation)   (None, 128)                  0         ['add_6[0][0]']

 dense_22 (Dense)            (None, 207)                  26703     ['activation_7[0][0]']

 batch_normalization_15 (Ba  (None, 207)                  828       ['dense_22[0][0]']
 tchNormalization)

 dense_23 (Dense)            (None, 207)                  43056     ['batch_normalization_15[0][0]
                                                                    ']

 batch_normalization_16 (Ba  (None, 207)                  828       ['dense_23[0][0]']
 tchNormalization)

 dense_24 (Dense)            (None, 207)                  26703     ['activation_7[0][0]']

 add_7 (Add)                 (None, 207)                  0         ['batch_normalization_16[0][0]
                                                                    ',
                                                                     'dense_24[0][0]']

 activation_8 (Activation)   (None, 207)                  0         ['add_7[0][0]']

 dense_25 (Dense)            (None, 174)                  36192     ['activation_8[0][0]']

 batch_normalization_17 (Ba  (None, 174)                  696       ['dense_25[0][0]']
 tchNormalization)

 dense_26 (Dense)            (None, 174)                  30450     ['batch_normalization_17[0][0]
                                                                    ']

 batch_normalization_18 (Ba  (None, 174)                  696       ['dense_26[0][0]']
 tchNormalization)

 dense_27 (Dense)            (None, 174)                  36192     ['activation_8[0][0]']

 add_8 (Add)                 (None, 174)                  0         ['batch_normalization_18[0][0]
                                                                    ',
                                                                     'dense_27[0][0]']

 activation_9 (Activation)   (None, 174)                  0         ['add_8[0][0]']

 dense_28 (Dense)            (None, 168)                  29400     ['activation_9[0][0]']

 batch_normalization_19 (Ba  (None, 168)                  672       ['dense_28[0][0]']
 tchNormalization)

 dense_29 (Dense)            (None, 168)                  28392     ['batch_normalization_19[0][0]
                                                                    ']

 batch_normalization_20 (Ba  (None, 168)                  672       ['dense_29[0][0]']
 tchNormalization)

 dense_30 (Dense)            (None, 168)                  29400     ['activation_9[0][0]']

 add_9 (Add)                 (None, 168)                  0         ['batch_normalization_20[0][0]
                                                                    ',
                                                                     'dense_30[0][0]']

 activation_10 (Activation)  (None, 168)                  0         ['add_9[0][0]']

 dense_31 (Dense)            (None, 178)                  30082     ['activation_10[0][0]']

 batch_normalization_21 (Ba  (None, 178)                  712       ['dense_31[0][0]']
 tchNormalization)

 dense_32 (Dense)            (None, 178)                  31862     ['batch_normalization_21[0][0]
                                                                    ']

 batch_normalization_22 (Ba  (None, 178)                  712       ['dense_32[0][0]']
 tchNormalization)

 dense_33 (Dense)            (None, 178)                  30082     ['activation_10[0][0]']

 add_10 (Add)                (None, 178)                  0         ['batch_normalization_22[0][0]
                                                                    ',
                                                                     'dense_33[0][0]']

 activation_11 (Activation)  (None, 178)                  0         ['add_10[0][0]']

 dense_34 (Dense)            (None, 131)                  23449     ['activation_11[0][0]']

 batch_normalization_23 (Ba  (None, 131)                  524       ['dense_34[0][0]']
 tchNormalization)

 dense_35 (Dense)            (None, 131)                  17292     ['batch_normalization_23[0][0]
                                                                    ']

 batch_normalization_24 (Ba  (None, 131)                  524       ['dense_35[0][0]']
 tchNormalization)

 dense_36 (Dense)            (None, 131)                  23449     ['activation_11[0][0]']

 add_11 (Add)                (None, 131)                  0         ['batch_normalization_24[0][0]
                                                                    ',
                                                                     'dense_36[0][0]']

 activation_12 (Activation)  (None, 131)                  0         ['add_11[0][0]']

 dense_37 (Dense)            (None, 129)                  17028     ['activation_12[0][0]']

 batch_normalization_25 (Ba  (None, 129)                  516       ['dense_37[0][0]']
 tchNormalization)

 dense_38 (Dense)            (None, 129)                  16770     ['batch_normalization_25[0][0]
                                                                    ']

 batch_normalization_26 (Ba  (None, 129)                  516       ['dense_38[0][0]']
 tchNormalization)

 dense_39 (Dense)            (None, 129)                  17028     ['activation_12[0][0]']

 add_12 (Add)                (None, 129)                  0         ['batch_normalization_26[0][0]
                                                                    ',
                                                                     'dense_39[0][0]']

 activation_13 (Activation)  (None, 129)                  0         ['add_12[0][0]']

 dense_40 (Dense)            (None, 208)                  27040     ['activation_13[0][0]']

 batch_normalization_27 (Ba  (None, 208)                  832       ['dense_40[0][0]']
 tchNormalization)

 dense_41 (Dense)            (None, 208)                  43472     ['batch_normalization_27[0][0]
                                                                    ']

 batch_normalization_28 (Ba  (None, 208)                  832       ['dense_41[0][0]']
 tchNormalization)

 dense_42 (Dense)            (None, 208)                  27040     ['activation_13[0][0]']

 add_13 (Add)                (None, 208)                  0         ['batch_normalization_28[0][0]
                                                                    ',
                                                                     'dense_42[0][0]']

 activation_14 (Activation)  (None, 208)                  0         ['add_13[0][0]']

 dense_43 (Dense)            (None, 189)                  39501     ['activation_14[0][0]']

 batch_normalization_29 (Ba  (None, 189)                  756       ['dense_43[0][0]']
 tchNormalization)

 dense_44 (Dense)            (None, 189)                  35910     ['batch_normalization_29[0][0]
                                                                    ']

 batch_normalization_30 (Ba  (None, 189)                  756       ['dense_44[0][0]']
 tchNormalization)

 dense_45 (Dense)            (None, 189)                  39501     ['activation_14[0][0]']

 add_14 (Add)                (None, 189)                  0         ['batch_normalization_30[0][0]
                                                                    ',
                                                                     'dense_45[0][0]']

 activation_15 (Activation)  (None, 189)                  0         ['add_14[0][0]']

 dense_46 (Dense)            (None, 181)                  34390     ['activation_15[0][0]']

 batch_normalization_31 (Ba  (None, 181)                  724       ['dense_46[0][0]']
 tchNormalization)

 dense_47 (Dense)            (None, 181)                  32942     ['batch_normalization_31[0][0]
                                                                    ']

 batch_normalization_32 (Ba  (None, 181)                  724       ['dense_47[0][0]']
 tchNormalization)

 dense_48 (Dense)            (None, 181)                  34390     ['activation_15[0][0]']

 add_15 (Add)                (None, 181)                  0         ['batch_normalization_32[0][0]
                                                                    ',
                                                                     'dense_48[0][0]']

 activation_16 (Activation)  (None, 181)                  0         ['add_15[0][0]']

 dense_49 (Dense)            (None, 131)                  23842     ['activation_16[0][0]']

 batch_normalization_33 (Ba  (None, 131)                  524       ['dense_49[0][0]']
 tchNormalization)

 dense_50 (Dense)            (None, 131)                  17292     ['batch_normalization_33[0][0]
                                                                    ']

 batch_normalization_34 (Ba  (None, 131)                  524       ['dense_50[0][0]']
 tchNormalization)

 dense_51 (Dense)            (None, 131)                  23842     ['activation_16[0][0]']

 add_16 (Add)                (None, 131)                  0         ['batch_normalization_34[0][0]
                                                                    ',
                                                                     'dense_51[0][0]']

 activation_17 (Activation)  (None, 131)                  0         ['add_16[0][0]']

 dense_52 (Dense)            (None, 130)                  17160     ['activation_17[0][0]']

 batch_normalization_35 (Ba  (None, 130)                  520       ['dense_52[0][0]']
 tchNormalization)

 dense_53 (Dense)            (None, 130)                  17030     ['batch_normalization_35[0][0]
                                                                    ']

 batch_normalization_36 (Ba  (None, 130)                  520       ['dense_53[0][0]']
 tchNormalization)

 dense_54 (Dense)            (None, 130)                  17160     ['activation_17[0][0]']

 add_17 (Add)                (None, 130)                  0         ['batch_normalization_36[0][0]
                                                                    ',
                                                                     'dense_54[0][0]']

 activation_18 (Activation)  (None, 130)                  0         ['add_17[0][0]']

 dropout (Dropout)           (None, 130)                  0         ['activation_18[0][0]']

 dense_55 (Dense)            (None, 1)                    131       ['dropout[0][0]']

==================================================================================================
Total params: 1795395 (6.85 MB)
Trainable params: 1782247 (6.80 MB)
Non-trainable params: 13148 (51.36 KB)
__________________________________________________________________________________________________
None
Epoch 1/200

2026-03-20 08:14:34.401649: I external/local_xla/xla/service/service.cc:168] XLA service 0x7865b40fe7e0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2026-03-20 08:14:34.401674: I external/local_xla/xla/service/service.cc:176]   StreamExecutor device (0): NVIDIA GeForce GTX 1650, Compute Capability 7.5
2026-03-20 08:14:34.406199: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
2026-03-20 08:14:34.421446: I external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:454] Loaded cuDNN version 8906
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1773994474.477276  125670 device_compiler.h:186] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.

54/54 [==============================] - 25s 56ms/step - loss: 0.5964 - accuracy: 0.7641 - precision: 0.8276 - auc: 0.7830 - auc_1: 0.9117 - val_loss: 0.3980 - val_accuracy: 0.8814 - val_precision: 0.9640 - val_auc: 0.9459 - val_auc_1: 0.9838 - lr: 9.8690e-04
Epoch 2/200
54/54 [==============================] - 2s 33ms/step - loss: 0.3877 - accuracy: 0.8600 - precision: 0.8998 - auc: 0.9123 - auc_1: 0.9673 - val_loss: 0.3845 - val_accuracy: 0.8539 - val_precision: 0.9196 - val_auc: 0.9263 - val_auc_1: 0.9775 - lr: 9.8690e-04
Epoch 3/200
54/54 [==============================] - 2s 34ms/step - loss: 0.3642 - accuracy: 0.8635 - precision: 0.8966 - auc: 0.9234 - auc_1: 0.9739 - val_loss: 0.2656 - val_accuracy: 0.8971 - val_precision: 0.9115 - val_auc: 0.9660 - val_auc_1: 0.9889 - lr: 9.8690e-04
Epoch 4/200
54/54 [==============================] - 2s 34ms/step - loss: 0.3794 - accuracy: 0.8706 - precision: 0.9055 - auc: 0.9174 - auc_1: 0.9642 - val_loss: 0.2514 - val_accuracy: 0.9382 - val_precision: 0.9986 - val_auc: 0.9833 - val_auc_1: 0.9951 - lr: 9.8690e-04
Epoch 5/200
54/54 [==============================] - 2s 34ms/step - loss: 0.2667 - accuracy: 0.9171 - precision: 0.9382 - auc: 0.9624 - auc_1: 0.9846 - val_loss: 0.1784 - val_accuracy: 0.9539 - val_precision: 0.9544 - val_auc: 0.9898 - val_auc_1: 0.9967 - lr: 9.8690e-04
Epoch 6/200
54/54 [==============================] - 2s 33ms/step - loss: 0.2248 - accuracy: 0.9335 - precision: 0.9518 - auc: 0.9751 - auc_1: 0.9904 - val_loss: 0.2212 - val_accuracy: 0.9245 - val_precision: 0.9873 - val_auc: 0.9898 - val_auc_1: 0.9967 - lr: 9.8690e-04
Epoch 7/200
54/54 [==============================] - 2s 34ms/step - loss: 0.1868 - accuracy: 0.9476 - precision: 0.9626 - auc: 0.9847 - auc_1: 0.9939 - val_loss: 0.1083 - val_accuracy: 0.9794 - val_precision: 0.9882 - val_auc: 0.9982 - val_auc_1: 0.9994 - lr: 9.8690e-04
Epoch 8/200
54/54 [==============================] - 2s 33ms/step - loss: 0.2483 - accuracy: 0.9218 - precision: 0.9413 - auc: 0.9699 - auc_1: 0.9878 - val_loss: 0.1477 - val_accuracy: 0.9676 - val_precision: 0.9803 - val_auc: 0.9966 - val_auc_1: 0.9989 - lr: 9.8690e-04
Epoch 9/200
54/54 [==============================] - 2s 33ms/step - loss: 0.2391 - accuracy: 0.9371 - precision: 0.9613 - auc: 0.9709 - auc_1: 0.9872 - val_loss: 0.1142 - val_accuracy: 0.9794 - val_precision: 0.9869 - val_auc: 0.9986 - val_auc_1: 0.9995 - lr: 9.8690e-04
Epoch 10/200
54/54 [==============================] - 2s 33ms/step - loss: 0.1766 - accuracy: 0.9547 - precision: 0.9672 - auc: 0.9860 - auc_1: 0.9944 - val_loss: 0.1113 - val_accuracy: 0.9755 - val_precision: 0.9780 - val_auc: 0.9986 - val_auc_1: 0.9995 - lr: 9.8690e-04
Epoch 11/200
54/54 [==============================] - 2s 34ms/step - loss: 0.1896 - accuracy: 0.9535 - precision: 0.9716 - auc: 0.9845 - auc_1: 0.9946 - val_loss: 0.0867 - val_accuracy: 0.9912 - val_precision: 0.9922 - val_auc: 0.9995 - val_auc_1: 0.9998 - lr: 9.8690e-04
Epoch 12/200
54/54 [==============================] - 2s 33ms/step - loss: 0.1448 - accuracy: 0.9647 - precision: 0.9772 - auc: 0.9924 - auc_1: 0.9972 - val_loss: 0.0904 - val_accuracy: 0.9853 - val_precision: 0.9820 - val_auc: 0.9998 - val_auc_1: 0.9999 - lr: 9.8690e-04
Epoch 13/200
54/54 [==============================] - 2s 33ms/step - loss: 0.1373 - accuracy: 0.9671 - precision: 0.9765 - auc: 0.9936 - auc_1: 0.9974 - val_loss: 0.1963 - val_accuracy: 0.9598 - val_precision: 0.9491 - val_auc: 0.9919 - val_auc_1: 0.9947 - lr: 9.8690e-04
Epoch 14/200
54/54 [==============================] - 2s 34ms/step - loss: 0.1312 - accuracy: 0.9724 - precision: 0.9797 - auc: 0.9933 - auc_1: 0.9969 - val_loss: 0.0812 - val_accuracy: 0.9931 - val_precision: 0.9935 - val_auc: 0.9997 - val_auc_1: 0.9999 - lr: 9.8690e-04
Epoch 15/200
54/54 [==============================] - 2s 34ms/step - loss: 0.1429 - accuracy: 0.9706 - precision: 0.9834 - auc: 0.9932 - auc_1: 0.9979 - val_loss: 0.0721 - val_accuracy: 0.9941 - val_precision: 0.9922 - val_auc: 1.0000 - val_auc_1: 1.0000 - lr: 9.8690e-04
Epoch 16/200
54/54 [==============================] - 2s 34ms/step - loss: 0.1749 - accuracy: 0.9594 - precision: 0.9718 - auc: 0.9864 - auc_1: 0.9942 - val_loss: 0.1237 - val_accuracy: 0.9725 - val_precision: 1.0000 - val_auc: 0.9986 - val_auc_1: 0.9996 - lr: 9.8690e-04
Epoch 17/200
54/54 [==============================] - 2s 34ms/step - loss: 0.2089 - accuracy: 0.9529 - precision: 0.9716 - auc: 0.9805 - auc_1: 0.9928 - val_loss: 0.1216 - val_accuracy: 0.9863 - val_precision: 0.9908 - val_auc: 0.9920 - val_auc_1: 0.9952 - lr: 9.8690e-04
Epoch 18/200
54/54 [==============================] - 2s 34ms/step - loss: 0.1437 - accuracy: 0.9688 - precision: 0.9819 - auc: 0.9923 - auc_1: 0.9971 - val_loss: 0.0880 - val_accuracy: 0.9873 - val_precision: 0.9858 - val_auc: 0.9977 - val_auc_1: 0.9986 - lr: 9.8690e-04
Epoch 19/200
54/54 [==============================] - 2s 34ms/step - loss: 0.1532 - accuracy: 0.9635 - precision: 0.9764 - auc: 0.9900 - auc_1: 0.9952 - val_loss: 0.0674 - val_accuracy: 0.9961 - val_precision: 1.0000 - val_auc: 1.0000 - val_auc_1: 1.0000 - lr: 9.8690e-04
Epoch 20/200
54/54 [==============================] - 2s 34ms/step - loss: 0.1276 - accuracy: 0.9824 - precision: 0.9929 - auc: 0.9932 - auc_1: 0.9976 - val_loss: 0.0765 - val_accuracy: 0.9971 - val_precision: 0.9974 - val_auc: 0.9999 - val_auc_1: 1.0000 - lr: 9.8690e-04
Epoch 21/200
54/54 [==============================] - 2s 34ms/step - loss: 0.1329 - accuracy: 0.9747 - precision: 0.9858 - auc: 0.9938 - auc_1: 0.9976 - val_loss: 0.1113 - val_accuracy: 0.9833 - val_precision: 0.9973 - val_auc: 0.9968 - val_auc_1: 0.9991 - lr: 9.8690e-04
Epoch 22/200
54/54 [==============================] - 2s 34ms/step - loss: 0.1256 - accuracy: 0.9782 - precision: 0.9889 - auc: 0.9944 - auc_1: 0.9978 - val_loss: 0.0890 - val_accuracy: 0.9892 - val_precision: 1.0000 - val_auc: 0.9999 - val_auc_1: 1.0000 - lr: 9.8690e-04
Epoch 23/200
54/54 [==============================] - 2s 34ms/step - loss: 0.1311 - accuracy: 0.9759 - precision: 0.9851 - auc: 0.9940 - auc_1: 0.9976 - val_loss: 0.0811 - val_accuracy: 0.9961 - val_precision: 0.9961 - val_auc: 0.9999 - val_auc_1: 1.0000 - lr: 9.8690e-04
Epoch 24/200
54/54 [==============================] - 2s 33ms/step - loss: 0.1365 - accuracy: 0.9694 - precision: 0.9766 - auc: 0.9936 - auc_1: 0.9975 - val_loss: 0.0918 - val_accuracy: 0.9863 - val_precision: 0.9820 - val_auc: 0.9999 - val_auc_1: 1.0000 - lr: 9.8690e-04
Epoch 25/200
54/54 [==============================] - 2s 33ms/step - loss: 0.1104 - accuracy: 0.9800 - precision: 0.9874 - auc: 0.9962 - auc_1: 0.9984 - val_loss: 0.0745 - val_accuracy: 0.9941 - val_precision: 0.9922 - val_auc: 0.9999 - val_auc_1: 1.0000 - lr: 9.8690e-05
Epoch 26/200
54/54 [==============================] - 2s 35ms/step - loss: 0.0929 - accuracy: 0.9882 - precision: 0.9906 - auc: 0.9958 - auc_1: 0.9973 - val_loss: 0.0633 - val_accuracy: 0.9980 - val_precision: 0.9974 - val_auc: 1.0000 - val_auc_1: 1.0000 - lr: 9.8690e-05
Epoch 27/200
54/54 [==============================] - 2s 34ms/step - loss: 0.0863 - accuracy: 0.9900 - precision: 0.9937 - auc: 0.9992 - auc_1: 0.9997 - val_loss: 0.0594 - val_accuracy: 1.0000 - val_precision: 1.0000 - val_auc: 1.0000 - val_auc_1: 1.0000 - lr: 9.8690e-05
Epoch 28/200
54/54 [==============================] - 2s 34ms/step - loss: 0.0889 - accuracy: 0.9900 - precision: 0.9953 - auc: 0.9984 - auc_1: 0.9995 - val_loss: 0.0597 - val_accuracy: 1.0000 - val_precision: 1.0000 - val_auc: 1.0000 - val_auc_1: 1.0000 - lr: 9.8690e-05
Epoch 29/200
54/54 [==============================] - 2s 34ms/step - loss: 0.0924 - accuracy: 0.9859 - precision: 0.9883 - auc: 0.9986 - auc_1: 0.9996 - val_loss: 0.0636 - val_accuracy: 0.9980 - val_precision: 0.9974 - val_auc: 1.0000 - val_auc_1: 1.0000 - lr: 9.8690e-05
Epoch 30/200
54/54 [==============================] - 2s 33ms/step - loss: 0.0910 - accuracy: 0.9912 - precision: 0.9907 - auc: 0.9981 - auc_1: 0.9989 - val_loss: 0.0599 - val_accuracy: 1.0000 - val_precision: 1.0000 - val_auc: 1.0000 - val_auc_1: 1.0000 - lr: 9.8690e-05
Epoch 31/200
54/54 [==============================] - 2s 33ms/step - loss: 0.0806 - accuracy: 0.9941 - precision: 0.9969 - auc: 0.9979 - auc_1: 0.9989 - val_loss: 0.0586 - val_accuracy: 1.0000 - val_precision: 1.0000 - val_auc: 1.0000 - val_auc_1: 1.0000 - lr: 9.8690e-05
Epoch 32/200
54/54 [==============================] - 2s 34ms/step - loss: 0.0865 - accuracy: 0.9924 - precision: 0.9945 - auc: 0.9977 - auc_1: 0.9988 - val_loss: 0.0597 - val_accuracy: 1.0000 - val_precision: 1.0000 - val_auc: 1.0000 - val_auc_1: 1.0000 - lr: 9.8690e-05
Epoch 33/200
54/54 [==============================] - 2s 33ms/step - loss: 0.0825 - accuracy: 0.9918 - precision: 0.9937 - auc: 0.9994 - auc_1: 0.9998 - val_loss: 0.0598 - val_accuracy: 1.0000 - val_precision: 1.0000 - val_auc: 1.0000 - val_auc_1: 1.0000 - lr: 9.8690e-05
Epoch 34/200
54/54 [==============================] - 2s 35ms/step - loss: 0.0921 - accuracy: 0.9900 - precision: 0.9922 - auc: 0.9969 - auc_1: 0.9987 - val_loss: 0.0590 - val_accuracy: 1.0000 - val_precision: 1.0000 - val_auc: 1.0000 - val_auc_1: 1.0000 - lr: 9.8690e-05

[I 2026-03-20 08:15:49,683] Trial 24 finished with value: 0.0 and parameters: {'activation': 'leaky_relu', 'regularizer_value_2': 8.548165211041157e-06, 'N_layers': 18, 'learning_rate': 0.0009868983135517442, 'optimizer': 'adamw', 'N_1st_layer': 180, 'Dropout': 'n', 'N_1_layer': 255, 'Dropout_value_L2': 0.14849899479398024, 'N_2_layer': 220, 'Dropout_value_L3': 0.14799639079739543, 'N_3_layer': 158, 'Dropout_value_L4': 0.11145652653120455, 'N_4_layer': 165, 'Dropout_value_L5': 0.10005105243930823, 'N_5_layer': 255, 'Dropout_value_L6': 0.14273072606166523, 'N_6_layer': 190, 'Dropout_value_L7': 0.10119597579589715, 'N_7_layer': 128, 'Dropout_value_L8': 0.11564993734590598, 'N_8_layer': 207, 'Dropout_value_L9': 0.11511264105736543, 'N_9_layer': 174, 'Dropout_value_L10': 0.123790119016271, 'N_10_layer': 168, 'Dropout_value_L11': 0.14978474586049, 'N_11_layer': 178, 'Dropout_value_L12': 0.1022869193852755, 'N_12_layer': 131, 'Dropout_value_L13': 0.10002455282537634, 'N_13_layer': 129, 'Dropout_value_L14': 0.10395356283437812, 'N_14_layer': 208, 'Dropout_value_L15': 0.10027089153394654, 'N_15_layer': 189, 'Dropout_value_L16': 0.10168917259517338, 'N_16_layer': 181, 'Dropout_value_L17': 0.11055489922727849, 'N_17_layer': 131, 'Dropout_value_L18': 0.100739131744828, 'N_18_layer': 130, 'Dropout_value_L19': 0.14779718456127544}. Best is trial 6 with value: 0.0.

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to
==================================================================================================
 input_1 (InputLayer)        [(None, 12)]                 0         []

 dense (Dense)               (None, 168)                  2184      ['input_1[0][0]']

 activation (Activation)     (None, 168)                  0         ['dense[0][0]']

 batch_normalization (Batch  (None, 168)                  672       ['activation[0][0]']
 Normalization)

 dense_1 (Dense)             (None, 252)                  42588     ['batch_normalization[0][0]']

 batch_normalization_1 (Bat  (None, 252)                  1008      ['dense_1[0][0]']
 chNormalization)

 dense_2 (Dense)             (None, 252)                  63756     ['batch_normalization_1[0][0]'
                                                                    ]

 batch_normalization_2 (Bat  (None, 252)                  1008      ['dense_2[0][0]']
 chNormalization)

 dense_3 (Dense)             (None, 252)                  42588     ['batch_normalization[0][0]']

 add (Add)                   (None, 252)                  0         ['batch_normalization_2[0][0]'
                                                                    , 'dense_3[0][0]']

 activation_1 (Activation)   (None, 252)                  0         ['add[0][0]']

 dense_4 (Dense)             (None, 230)                  58190     ['activation_1[0][0]']

 batch_normalization_3 (Bat  (None, 230)                  920       ['dense_4[0][0]']
 chNormalization)

 dense_5 (Dense)             (None, 230)                  53130     ['batch_normalization_3[0][0]'
                                                                    ]

 batch_normalization_4 (Bat  (None, 230)                  920       ['dense_5[0][0]']
 chNormalization)

 dense_6 (Dense)             (None, 230)                  58190     ['activation_1[0][0]']

 add_1 (Add)                 (None, 230)                  0         ['batch_normalization_4[0][0]'
                                                                    , 'dense_6[0][0]']

 activation_2 (Activation)   (None, 230)                  0         ['add_1[0][0]']

 dense_7 (Dense)             (None, 166)                  38346     ['activation_2[0][0]']

 batch_normalization_5 (Bat  (None, 166)                  664       ['dense_7[0][0]']
 chNormalization)

 dense_8 (Dense)             (None, 166)                  27722     ['batch_normalization_5[0][0]'
                                                                    ]

 batch_normalization_6 (Bat  (None, 166)                  664       ['dense_8[0][0]']
 chNormalization)

 dense_9 (Dense)             (None, 166)                  38346     ['activation_2[0][0]']

 add_2 (Add)                 (None, 166)                  0         ['batch_normalization_6[0][0]'
                                                                    , 'dense_9[0][0]']

 activation_3 (Activation)   (None, 166)                  0         ['add_2[0][0]']

 dense_10 (Dense)            (None, 155)                  25885     ['activation_3[0][0]']

 batch_normalization_7 (Bat  (None, 155)                  620       ['dense_10[0][0]']
 chNormalization)

 dense_11 (Dense)            (None, 155)                  24180     ['batch_normalization_7[0][0]'
                                                                    ]

 batch_normalization_8 (Bat  (None, 155)                  620       ['dense_11[0][0]']
 chNormalization)

 dense_12 (Dense)            (None, 155)                  25885     ['activation_3[0][0]']

 add_3 (Add)                 (None, 155)                  0         ['batch_normalization_8[0][0]'
                                                                    , 'dense_12[0][0]']

 activation_4 (Activation)   (None, 155)                  0         ['add_3[0][0]']

 dense_13 (Dense)            (None, 246)                  38376     ['activation_4[0][0]']

 batch_normalization_9 (Bat  (None, 246)                  984       ['dense_13[0][0]']
 chNormalization)

 dense_14 (Dense)            (None, 246)                  60762     ['batch_normalization_9[0][0]'
                                                                    ]

 batch_normalization_10 (Ba  (None, 246)                  984       ['dense_14[0][0]']
 tchNormalization)

 dense_15 (Dense)            (None, 246)                  38376     ['activation_4[0][0]']

 add_4 (Add)                 (None, 246)                  0         ['batch_normalization_10[0][0]
                                                                    ',
                                                                     'dense_15[0][0]']

 activation_5 (Activation)   (None, 246)                  0         ['add_4[0][0]']

 dense_16 (Dense)            (None, 192)                  47424     ['activation_5[0][0]']

 batch_normalization_11 (Ba  (None, 192)                  768       ['dense_16[0][0]']
 tchNormalization)

 dense_17 (Dense)            (None, 192)                  37056     ['batch_normalization_11[0][0]
                                                                    ']

 batch_normalization_12 (Ba  (None, 192)                  768       ['dense_17[0][0]']
 tchNormalization)

 dense_18 (Dense)            (None, 192)                  47424     ['activation_5[0][0]']

 add_5 (Add)                 (None, 192)                  0         ['batch_normalization_12[0][0]
                                                                    ',
                                                                     'dense_18[0][0]']

 activation_6 (Activation)   (None, 192)                  0         ['add_5[0][0]']

 dense_19 (Dense)            (None, 140)                  27020     ['activation_6[0][0]']

 batch_normalization_13 (Ba  (None, 140)                  560       ['dense_19[0][0]']
 tchNormalization)

 dense_20 (Dense)            (None, 140)                  19740     ['batch_normalization_13[0][0]
                                                                    ']

 batch_normalization_14 (Ba  (None, 140)                  560       ['dense_20[0][0]']
 tchNormalization)

 dense_21 (Dense)            (None, 140)                  27020     ['activation_6[0][0]']

 add_6 (Add)                 (None, 140)                  0         ['batch_normalization_14[0][0]
                                                                    ',
                                                                     'dense_21[0][0]']

 activation_7 (Activation)   (None, 140)                  0         ['add_6[0][0]']

 dense_22 (Dense)            (None, 204)                  28764     ['activation_7[0][0]']

 batch_normalization_15 (Ba  (None, 204)                  816       ['dense_22[0][0]']
 tchNormalization)

 dense_23 (Dense)            (None, 204)                  41820     ['batch_normalization_15[0][0]
                                                                    ']

 batch_normalization_16 (Ba  (None, 204)                  816       ['dense_23[0][0]']
 tchNormalization)

 dense_24 (Dense)            (None, 204)                  28764     ['activation_7[0][0]']

 add_7 (Add)                 (None, 204)                  0         ['batch_normalization_16[0][0]
                                                                    ',
                                                                     'dense_24[0][0]']

 activation_8 (Activation)   (None, 204)                  0         ['add_7[0][0]']

 dense_25 (Dense)            (None, 157)                  32185     ['activation_8[0][0]']

 batch_normalization_17 (Ba  (None, 157)                  628       ['dense_25[0][0]']
 tchNormalization)

 dense_26 (Dense)            (None, 157)                  24806     ['batch_normalization_17[0][0]
                                                                    ']

 batch_normalization_18 (Ba  (None, 157)                  628       ['dense_26[0][0]']
 tchNormalization)

 dense_27 (Dense)            (None, 157)                  32185     ['activation_8[0][0]']

 add_8 (Add)                 (None, 157)                  0         ['batch_normalization_18[0][0]
                                                                    ',
                                                                     'dense_27[0][0]']

 activation_9 (Activation)   (None, 157)                  0         ['add_8[0][0]']

 dense_28 (Dense)            (None, 147)                  23226     ['activation_9[0][0]']

 batch_normalization_19 (Ba  (None, 147)                  588       ['dense_28[0][0]']
 tchNormalization)

 dense_29 (Dense)            (None, 147)                  21756     ['batch_normalization_19[0][0]
                                                                    ']

 batch_normalization_20 (Ba  (None, 147)                  588       ['dense_29[0][0]']
 tchNormalization)

 dense_30 (Dense)            (None, 147)                  23226     ['activation_9[0][0]']

 add_9 (Add)                 (None, 147)                  0         ['batch_normalization_20[0][0]
                                                                    ',
                                                                     'dense_30[0][0]']

 activation_10 (Activation)  (None, 147)                  0         ['add_9[0][0]']

 dense_31 (Dense)            (None, 181)                  26788     ['activation_10[0][0]']

 batch_normalization_21 (Ba  (None, 181)                  724       ['dense_31[0][0]']
 tchNormalization)

 dense_32 (Dense)            (None, 181)                  32942     ['batch_normalization_21[0][0]
                                                                    ']

 batch_normalization_22 (Ba  (None, 181)                  724       ['dense_32[0][0]']
 tchNormalization)

 dense_33 (Dense)            (None, 181)                  26788     ['activation_10[0][0]']

 add_10 (Add)                (None, 181)                  0         ['batch_normalization_22[0][0]
                                                                    ',
                                                                     'dense_33[0][0]']

 activation_11 (Activation)  (None, 181)                  0         ['add_10[0][0]']

 dense_34 (Dense)            (None, 139)                  25298     ['activation_11[0][0]']

 batch_normalization_23 (Ba  (None, 139)                  556       ['dense_34[0][0]']
 tchNormalization)

 dense_35 (Dense)            (None, 139)                  19460     ['batch_normalization_23[0][0]
                                                                    ']

 batch_normalization_24 (Ba  (None, 139)                  556       ['dense_35[0][0]']
 tchNormalization)

 dense_36 (Dense)            (None, 139)                  25298     ['activation_11[0][0]']

 add_11 (Add)                (None, 139)                  0         ['batch_normalization_24[0][0]
                                                                    ',
                                                                     'dense_36[0][0]']

 activation_12 (Activation)  (None, 139)                  0         ['add_11[0][0]']

 dense_37 (Dense)            (None, 128)                  17920     ['activation_12[0][0]']

 batch_normalization_25 (Ba  (None, 128)                  512       ['dense_37[0][0]']
 tchNormalization)

 dense_38 (Dense)            (None, 128)                  16512     ['batch_normalization_25[0][0]
                                                                    ']

 batch_normalization_26 (Ba  (None, 128)                  512       ['dense_38[0][0]']
 tchNormalization)

 dense_39 (Dense)            (None, 128)                  17920     ['activation_12[0][0]']

 add_12 (Add)                (None, 128)                  0         ['batch_normalization_26[0][0]
                                                                    ',
                                                                     'dense_39[0][0]']

 activation_13 (Activation)  (None, 128)                  0         ['add_12[0][0]']

 dense_40 (Dense)            (None, 212)                  27348     ['activation_13[0][0]']

 batch_normalization_27 (Ba  (None, 212)                  848       ['dense_40[0][0]']
 tchNormalization)

 dense_41 (Dense)            (None, 212)                  45156     ['batch_normalization_27[0][0]
                                                                    ']

 batch_normalization_28 (Ba  (None, 212)                  848       ['dense_41[0][0]']
 tchNormalization)

 dense_42 (Dense)            (None, 212)                  27348     ['activation_13[0][0]']

 add_13 (Add)                (None, 212)                  0         ['batch_normalization_28[0][0]
                                                                    ',
                                                                     'dense_42[0][0]']

 activation_14 (Activation)  (None, 212)                  0         ['add_13[0][0]']

 dense_43 (Dense)            (None, 173)                  36849     ['activation_14[0][0]']

 batch_normalization_29 (Ba  (None, 173)                  692       ['dense_43[0][0]']
 tchNormalization)

 dense_44 (Dense)            (None, 173)                  30102     ['batch_normalization_29[0][0]
                                                                    ']

 batch_normalization_30 (Ba  (None, 173)                  692       ['dense_44[0][0]']
 tchNormalization)

 dense_45 (Dense)            (None, 173)                  36849     ['activation_14[0][0]']

 add_14 (Add)                (None, 173)                  0         ['batch_normalization_30[0][0]
                                                                    ',
                                                                     'dense_45[0][0]']

 activation_15 (Activation)  (None, 173)                  0         ['add_14[0][0]']

 dense_46 (Dense)            (None, 151)                  26274     ['activation_15[0][0]']

 batch_normalization_31 (Ba  (None, 151)                  604       ['dense_46[0][0]']
 tchNormalization)

 dense_47 (Dense)            (None, 151)                  22952     ['batch_normalization_31[0][0]
                                                                    ']

 batch_normalization_32 (Ba  (None, 151)                  604       ['dense_47[0][0]']
 tchNormalization)

 dense_48 (Dense)            (None, 151)                  26274     ['activation_15[0][0]']

 add_15 (Add)                (None, 151)                  0         ['batch_normalization_32[0][0]
                                                                    ',
                                                                     'dense_48[0][0]']

 activation_16 (Activation)  (None, 151)                  0         ['add_15[0][0]']

 dense_49 (Dense)            (None, 129)                  19608     ['activation_16[0][0]']

 batch_normalization_33 (Ba  (None, 129)                  516       ['dense_49[0][0]']
 tchNormalization)

 dense_50 (Dense)            (None, 129)                  16770     ['batch_normalization_33[0][0]
                                                                    ']

 batch_normalization_34 (Ba  (None, 129)                  516       ['dense_50[0][0]']
 tchNormalization)

 dense_51 (Dense)            (None, 129)                  19608     ['activation_16[0][0]']

 add_16 (Add)                (None, 129)                  0         ['batch_normalization_34[0][0]
                                                                    ',
                                                                     'dense_51[0][0]']

 activation_17 (Activation)  (None, 129)                  0         ['add_16[0][0]']

 dense_52 (Dense)            (None, 135)                  17550     ['activation_17[0][0]']

 batch_normalization_35 (Ba  (None, 135)                  540       ['dense_52[0][0]']
 tchNormalization)

 dense_53 (Dense)            (None, 135)                  18360     ['batch_normalization_35[0][0]
                                                                    ']

 batch_normalization_36 (Ba  (None, 135)                  540       ['dense_53[0][0]']
 tchNormalization)

 dense_54 (Dense)            (None, 135)                  17550     ['activation_17[0][0]']

 add_17 (Add)                (None, 135)                  0         ['batch_normalization_36[0][0]
                                                                    ',
                                                                     'dense_54[0][0]']

 activation_18 (Activation)  (None, 135)                  0         ['add_17[0][0]']

 dense_55 (Dense)            (None, 254)                  34544     ['activation_18[0][0]']

 batch_normalization_37 (Ba  (None, 254)                  1016      ['dense_55[0][0]']
 tchNormalization)

 dense_56 (Dense)            (None, 254)                  64770     ['batch_normalization_37[0][0]
                                                                    ']

 batch_normalization_38 (Ba  (None, 254)                  1016      ['dense_56[0][0]']
 tchNormalization)

 dense_57 (Dense)            (None, 254)                  34544     ['activation_18[0][0]']

 add_18 (Add)                (None, 254)                  0         ['batch_normalization_38[0][0]
                                                                    ',
                                                                     'dense_57[0][0]']

 activation_19 (Activation)  (None, 254)                  0         ['add_18[0][0]']

 dropout (Dropout)           (None, 254)                  0         ['activation_19[0][0]']

 dense_58 (Dense)            (None, 1)                    255       ['dropout[0][0]']

==================================================================================================
Total params: 1860357 (7.10 MB)
Trainable params: 1846457 (7.04 MB)
Non-trainable params: 13900 (54.30 KB)
__________________________________________________________________________________________________
None
Epoch 1/200
54/54 [==============================] - 25s 60ms/step - loss: 0.6004 - accuracy: 0.7729 - precision: 0.8360 - auc: 0.7825 - auc_1: 0.9114 - val_loss: 0.4662 - val_accuracy: 0.8235 - val_precision: 0.9933 - val_auc: 0.9616 - val_auc_1: 0.9876 - lr: 8.4254e-04
Epoch 2/200
54/54 [==============================] - 2s 36ms/step - loss: 0.3832 - accuracy: 0.8635 - precision: 0.9033 - auc: 0.9199 - auc_1: 0.9670 - val_loss: 0.3907 - val_accuracy: 0.8431 - val_precision: 0.9919 - val_auc: 0.9723 - val_auc_1: 0.9911 - lr: 8.4254e-04
Epoch 3/200
54/54 [==============================] - 2s 37ms/step - loss: 0.3041 - accuracy: 0.8947 - precision: 0.9363 - auc: 0.9516 - auc_1: 0.9833 - val_loss: 0.2638 - val_accuracy: 0.9000 - val_precision: 0.9882 - val_auc: 0.9843 - val_auc_1: 0.9949 - lr: 8.4254e-04
Epoch 4/200
54/54 [==============================] - 2s 36ms/step - loss: 0.2547 - accuracy: 0.9182 - precision: 0.9479 - auc: 0.9705 - auc_1: 0.9906 - val_loss: 0.2310 - val_accuracy: 0.9245 - val_precision: 0.9943 - val_auc: 0.9932 - val_auc_1: 0.9978 - lr: 8.4254e-04
Epoch 5/200
54/54 [==============================] - 2s 36ms/step - loss: 0.2115 - accuracy: 0.9365 - precision: 0.9548 - auc: 0.9811 - auc_1: 0.9934 - val_loss: 0.1541 - val_accuracy: 0.9676 - val_precision: 0.9946 - val_auc: 0.9956 - val_auc_1: 0.9986 - lr: 8.4254e-04
Epoch 6/200
54/54 [==============================] - 2s 35ms/step - loss: 0.1866 - accuracy: 0.9547 - precision: 0.9717 - auc: 0.9853 - auc_1: 0.9945 - val_loss: 0.1758 - val_accuracy: 0.9520 - val_precision: 0.9972 - val_auc: 0.9988 - val_auc_1: 0.9996 - lr: 8.4254e-04
Epoch 7/200

[I 2026-03-20 08:17:06,668] Trial 25 finished with value: 0.0 and parameters: {'activation': 'leaky_relu', 'regularizer_value_2': 8.696842499379198e-06, 'N_layers': 19, 'learning_rate': 0.0008425419392662155, 'optimizer': 'adamw', 'N_1st_layer': 168, 'Dropout': 'n', 'N_1_layer': 252, 'Dropout_value_L2': 0.14602372350025195, 'N_2_layer': 230, 'Dropout_value_L3': 0.14945693956576664, 'N_3_layer': 166, 'Dropout_value_L4': 0.11764751751008246, 'N_4_layer': 155, 'Dropout_value_L5': 0.10127197404502342, 'N_5_layer': 246, 'Dropout_value_L6': 0.14411280898071344, 'N_6_layer': 192, 'Dropout_value_L7': 0.10932767030725651, 'N_7_layer': 140, 'Dropout_value_L8': 0.1201348869751292, 'N_8_layer': 204, 'Dropout_value_L9': 0.10298635894132635, 'N_9_layer': 157, 'Dropout_value_L10': 0.12558602559401888, 'N_10_layer': 147, 'Dropout_value_L11': 0.1460051827090058, 'N_11_layer': 181, 'Dropout_value_L12': 0.10960509073600669, 'N_12_layer': 139, 'Dropout_value_L13': 0.10479549111304674, 'N_13_layer': 128, 'Dropout_value_L14': 0.1080404724841087, 'N_14_layer': 212, 'Dropout_value_L15': 0.10493840430959853, 'N_15_layer': 173, 'Dropout_value_L16': 0.10045199522276554, 'N_16_layer': 151, 'Dropout_value_L17': 0.10124702402806748, 'N_17_layer': 129, 'Dropout_value_L18': 0.10742474527296357, 'N_18_layer': 135, 'Dropout_value_L19': 0.1360503151240734, 'N_19_layer': 254, 'Dropout_value_L20': 0.12656837526326303}. Best is trial 6 with value: 0.0.

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to
==================================================================================================
 input_1 (InputLayer)        [(None, 12)]                 0         []

 dense (Dense)               (None, 165)                  2145      ['input_1[0][0]']

 activation (Activation)     (None, 165)                  0         ['dense[0][0]']

 batch_normalization (Batch  (None, 165)                  660       ['activation[0][0]']
 Normalization)

 dense_1 (Dense)             (None, 227)                  37682     ['batch_normalization[0][0]']

 batch_normalization_1 (Bat  (None, 227)                  908       ['dense_1[0][0]']
 chNormalization)

 dense_2 (Dense)             (None, 227)                  51756     ['batch_normalization_1[0][0]'
                                                                    ]

 batch_normalization_2 (Bat  (None, 227)                  908       ['dense_2[0][0]']
 chNormalization)

 dense_3 (Dense)             (None, 227)                  37682     ['batch_normalization[0][0]']

 add (Add)                   (None, 227)                  0         ['batch_normalization_2[0][0]'
                                                                    , 'dense_3[0][0]']

 activation_1 (Activation)   (None, 227)                  0         ['add[0][0]']

 dense_4 (Dense)             (None, 203)                  46284     ['activation_1[0][0]']

 batch_normalization_3 (Bat  (None, 203)                  812       ['dense_4[0][0]']
 chNormalization)

 dense_5 (Dense)             (None, 203)                  41412     ['batch_normalization_3[0][0]'
                                                                    ]

 batch_normalization_4 (Bat  (None, 203)                  812       ['dense_5[0][0]']
 chNormalization)

 dense_6 (Dense)             (None, 203)                  46284     ['activation_1[0][0]']

 add_1 (Add)                 (None, 203)                  0         ['batch_normalization_4[0][0]'
                                                                    , 'dense_6[0][0]']

 activation_2 (Activation)   (None, 203)                  0         ['add_1[0][0]']

 dense_7 (Dense)             (None, 153)                  31212     ['activation_2[0][0]']

 batch_normalization_5 (Bat  (None, 153)                  612       ['dense_7[0][0]']
 chNormalization)

 dense_8 (Dense)             (None, 153)                  23562     ['batch_normalization_5[0][0]'
                                                                    ]

 batch_normalization_6 (Bat  (None, 153)                  612       ['dense_8[0][0]']
 chNormalization)

 dense_9 (Dense)             (None, 153)                  31212     ['activation_2[0][0]']

 add_2 (Add)                 (None, 153)                  0         ['batch_normalization_6[0][0]'
                                                                    , 'dense_9[0][0]']

 activation_3 (Activation)   (None, 153)                  0         ['add_2[0][0]']

 dense_10 (Dense)            (None, 133)                  20482     ['activation_3[0][0]']

 batch_normalization_7 (Bat  (None, 133)                  532       ['dense_10[0][0]']
 chNormalization)

 dense_11 (Dense)            (None, 133)                  17822     ['batch_normalization_7[0][0]'
                                                                    ]

 batch_normalization_8 (Bat  (None, 133)                  532       ['dense_11[0][0]']
 chNormalization)

 dense_12 (Dense)            (None, 133)                  20482     ['activation_3[0][0]']

 add_3 (Add)                 (None, 133)                  0         ['batch_normalization_8[0][0]'
                                                                    , 'dense_12[0][0]']

 activation_4 (Activation)   (None, 133)                  0         ['add_3[0][0]']

 dense_13 (Dense)            (None, 245)                  32830     ['activation_4[0][0]']

 batch_normalization_9 (Bat  (None, 245)                  980       ['dense_13[0][0]']
 chNormalization)

 dense_14 (Dense)            (None, 245)                  60270     ['batch_normalization_9[0][0]'
                                                                    ]

 batch_normalization_10 (Ba  (None, 245)                  980       ['dense_14[0][0]']
 tchNormalization)

 dense_15 (Dense)            (None, 245)                  32830     ['activation_4[0][0]']

 add_4 (Add)                 (None, 245)                  0         ['batch_normalization_10[0][0]
                                                                    ',
                                                                     'dense_15[0][0]']

 activation_5 (Activation)   (None, 245)                  0         ['add_4[0][0]']

 dense_16 (Dense)            (None, 221)                  54366     ['activation_5[0][0]']

 batch_normalization_11 (Ba  (None, 221)                  884       ['dense_16[0][0]']
 tchNormalization)

 dense_17 (Dense)            (None, 221)                  49062     ['batch_normalization_11[0][0]
                                                                    ']

 batch_normalization_12 (Ba  (None, 221)                  884       ['dense_17[0][0]']
 tchNormalization)

 dense_18 (Dense)            (None, 221)                  54366     ['activation_5[0][0]']

 add_5 (Add)                 (None, 221)                  0         ['batch_normalization_12[0][0]
                                                                    ',
                                                                     'dense_18[0][0]']

 activation_6 (Activation)   (None, 221)                  0         ['add_5[0][0]']

 dense_19 (Dense)            (None, 140)                  31080     ['activation_6[0][0]']

 batch_normalization_13 (Ba  (None, 140)                  560       ['dense_19[0][0]']
 tchNormalization)

 dense_20 (Dense)            (None, 140)                  19740     ['batch_normalization_13[0][0]
                                                                    ']

 batch_normalization_14 (Ba  (None, 140)                  560       ['dense_20[0][0]']
 tchNormalization)

 dense_21 (Dense)            (None, 140)                  31080     ['activation_6[0][0]']

 add_6 (Add)                 (None, 140)                  0         ['batch_normalization_14[0][0]
                                                                    ',
                                                                     'dense_21[0][0]']

 activation_7 (Activation)   (None, 140)                  0         ['add_6[0][0]']

 dense_22 (Dense)            (None, 225)                  31725     ['activation_7[0][0]']

 batch_normalization_15 (Ba  (None, 225)                  900       ['dense_22[0][0]']
 tchNormalization)

 dense_23 (Dense)            (None, 225)                  50850     ['batch_normalization_15[0][0]
                                                                    ']

 batch_normalization_16 (Ba  (None, 225)                  900       ['dense_23[0][0]']
 tchNormalization)

 dense_24 (Dense)            (None, 225)                  31725     ['activation_7[0][0]']

 add_7 (Add)                 (None, 225)                  0         ['batch_normalization_16[0][0]
                                                                    ',
                                                                     'dense_24[0][0]']

 activation_8 (Activation)   (None, 225)                  0         ['add_7[0][0]']

 dense_25 (Dense)            (None, 199)                  44974     ['activation_8[0][0]']

 batch_normalization_17 (Ba  (None, 199)                  796       ['dense_25[0][0]']
 tchNormalization)

 dense_26 (Dense)            (None, 199)                  39800     ['batch_normalization_17[0][0]
                                                                    ']

 batch_normalization_18 (Ba  (None, 199)                  796       ['dense_26[0][0]']
 tchNormalization)

 dense_27 (Dense)            (None, 199)                  44974     ['activation_8[0][0]']

 add_8 (Add)                 (None, 199)                  0         ['batch_normalization_18[0][0]
                                                                    ',
                                                                     'dense_27[0][0]']

 activation_9 (Activation)   (None, 199)                  0         ['add_8[0][0]']

 dense_28 (Dense)            (None, 170)                  34000     ['activation_9[0][0]']

 batch_normalization_19 (Ba  (None, 170)                  680       ['dense_28[0][0]']
 tchNormalization)

 dense_29 (Dense)            (None, 170)                  29070     ['batch_normalization_19[0][0]
                                                                    ']

 batch_normalization_20 (Ba  (None, 170)                  680       ['dense_29[0][0]']
 tchNormalization)

 dense_30 (Dense)            (None, 170)                  34000     ['activation_9[0][0]']

 add_9 (Add)                 (None, 170)                  0         ['batch_normalization_20[0][0]
                                                                    ',
                                                                     'dense_30[0][0]']

 activation_10 (Activation)  (None, 170)                  0         ['add_9[0][0]']

 dense_31 (Dense)            (None, 161)                  27531     ['activation_10[0][0]']

 batch_normalization_21 (Ba  (None, 161)                  644       ['dense_31[0][0]']
 tchNormalization)

 dense_32 (Dense)            (None, 161)                  26082     ['batch_normalization_21[0][0]
                                                                    ']

 batch_normalization_22 (Ba  (None, 161)                  644       ['dense_32[0][0]']
 tchNormalization)

 dense_33 (Dense)            (None, 161)                  27531     ['activation_10[0][0]']

 add_10 (Add)                (None, 161)                  0         ['batch_normalization_22[0][0]
                                                                    ',
                                                                     'dense_33[0][0]']

 activation_11 (Activation)  (None, 161)                  0         ['add_10[0][0]']

 dense_34 (Dense)            (None, 162)                  26244     ['activation_11[0][0]']

 batch_normalization_23 (Ba  (None, 162)                  648       ['dense_34[0][0]']
 tchNormalization)

 dense_35 (Dense)            (None, 162)                  26406     ['batch_normalization_23[0][0]
                                                                    ']

 batch_normalization_24 (Ba  (None, 162)                  648       ['dense_35[0][0]']
 tchNormalization)

 dense_36 (Dense)            (None, 162)                  26244     ['activation_11[0][0]']

 add_11 (Add)                (None, 162)                  0         ['batch_normalization_24[0][0]
                                                                    ',
                                                                     'dense_36[0][0]']

 activation_12 (Activation)  (None, 162)                  0         ['add_11[0][0]']

 dense_37 (Dense)            (None, 145)                  23635     ['activation_12[0][0]']

 batch_normalization_25 (Ba  (None, 145)                  580       ['dense_37[0][0]']
 tchNormalization)

 dense_38 (Dense)            (None, 145)                  21170     ['batch_normalization_25[0][0]
                                                                    ']

 batch_normalization_26 (Ba  (None, 145)                  580       ['dense_38[0][0]']
 tchNormalization)

 dense_39 (Dense)            (None, 145)                  23635     ['activation_12[0][0]']

 add_12 (Add)                (None, 145)                  0         ['batch_normalization_26[0][0]
                                                                    ',
                                                                     'dense_39[0][0]']

 activation_13 (Activation)  (None, 145)                  0         ['add_12[0][0]']

 dense_40 (Dense)            (None, 197)                  28762     ['activation_13[0][0]']

 batch_normalization_27 (Ba  (None, 197)                  788       ['dense_40[0][0]']
 tchNormalization)

 dense_41 (Dense)            (None, 197)                  39006     ['batch_normalization_27[0][0]
                                                                    ']

 batch_normalization_28 (Ba  (None, 197)                  788       ['dense_41[0][0]']
 tchNormalization)

 dense_42 (Dense)            (None, 197)                  28762     ['activation_13[0][0]']

 add_13 (Add)                (None, 197)                  0         ['batch_normalization_28[0][0]
                                                                    ',
                                                                     'dense_42[0][0]']

 activation_14 (Activation)  (None, 197)                  0         ['add_13[0][0]']

 dense_43 (Dense)            (None, 146)                  28908     ['activation_14[0][0]']

 batch_normalization_29 (Ba  (None, 146)                  584       ['dense_43[0][0]']
 tchNormalization)

 dense_44 (Dense)            (None, 146)                  21462     ['batch_normalization_29[0][0]
                                                                    ']

 batch_normalization_30 (Ba  (None, 146)                  584       ['dense_44[0][0]']
 tchNormalization)

 dense_45 (Dense)            (None, 146)                  28908     ['activation_14[0][0]']

 add_14 (Add)                (None, 146)                  0         ['batch_normalization_30[0][0]
                                                                    ',
                                                                     'dense_45[0][0]']

 activation_15 (Activation)  (None, 146)                  0         ['add_14[0][0]']

 dense_46 (Dense)            (None, 208)                  30576     ['activation_15[0][0]']

 batch_normalization_31 (Ba  (None, 208)                  832       ['dense_46[0][0]']
 tchNormalization)

 dense_47 (Dense)            (None, 208)                  43472     ['batch_normalization_31[0][0]
                                                                    ']

 batch_normalization_32 (Ba  (None, 208)                  832       ['dense_47[0][0]']
 tchNormalization)

 dense_48 (Dense)            (None, 208)                  30576     ['activation_15[0][0]']

 add_15 (Add)                (None, 208)                  0         ['batch_normalization_32[0][0]
                                                                    ',
                                                                     'dense_48[0][0]']

 activation_16 (Activation)  (None, 208)                  0         ['add_15[0][0]']

 dense_49 (Dense)            (None, 147)                  30723     ['activation_16[0][0]']

 batch_normalization_33 (Ba  (None, 147)                  588       ['dense_49[0][0]']
 tchNormalization)

 dense_50 (Dense)            (None, 147)                  21756     ['batch_normalization_33[0][0]
                                                                    ']

 batch_normalization_34 (Ba  (None, 147)                  588       ['dense_50[0][0]']
 tchNormalization)

 dense_51 (Dense)            (None, 147)                  30723     ['activation_16[0][0]']

 add_16 (Add)                (None, 147)                  0         ['batch_normalization_34[0][0]
                                                                    ',
                                                                     'dense_51[0][0]']

 activation_17 (Activation)  (None, 147)                  0         ['add_16[0][0]']

 dense_52 (Dense)            (None, 175)                  25900     ['activation_17[0][0]']

 batch_normalization_35 (Ba  (None, 175)                  700       ['dense_52[0][0]']
 tchNormalization)

 dense_53 (Dense)            (None, 175)                  30800     ['batch_normalization_35[0][0]
                                                                    ']

 batch_normalization_36 (Ba  (None, 175)                  700       ['dense_53[0][0]']
 tchNormalization)

 dense_54 (Dense)            (None, 175)                  25900     ['activation_17[0][0]']

 add_17 (Add)                (None, 175)                  0         ['batch_normalization_36[0][0]
                                                                    ',
                                                                     'dense_54[0][0]']

 activation_18 (Activation)  (None, 175)                  0         ['add_17[0][0]']

 dropout (Dropout)           (None, 175)                  0         ['activation_18[0][0]']

 dense_55 (Dense)            (None, 1)                    176       ['dropout[0][0]']

==================================================================================================
Total params: 1816363 (6.93 MB)
Trainable params: 1803005 (6.88 MB)
Non-trainable params: 13358 (52.18 KB)
__________________________________________________________________________________________________
None
Epoch 1/200
54/54 [==============================] - 23s 53ms/step - loss: 0.5966 - accuracy: 0.7629 - precision: 0.8182 - auc: 0.7318 - auc_1: 0.8734 - val_loss: 0.4636 - val_accuracy: 0.8725 - val_precision: 0.9183 - val_auc: 0.9245 - val_auc_1: 0.9682 - lr: 7.8519e-04
Epoch 2/200
54/54 [==============================] - 2s 34ms/step - loss: 0.3827 - accuracy: 0.8576 - precision: 0.9013 - auc: 0.9058 - auc_1: 0.9637 - val_loss: 0.3346 - val_accuracy: 0.8706 - val_precision: 0.9402 - val_auc: 0.9497 - val_auc_1: 0.9839 - lr: 7.8519e-04
Epoch 3/200
54/54 [==============================] - 2s 35ms/step - loss: 0.3657 - accuracy: 0.8429 - precision: 0.8865 - auc: 0.9129 - auc_1: 0.9684 - val_loss: 0.4009 - val_accuracy: 0.8471 - val_precision: 0.9344 - val_auc: 0.9290 - val_auc_1: 0.9764 - lr: 7.8519e-04
Epoch 4/200
54/54 [==============================] - 2s 34ms/step - loss: 0.3227 - accuracy: 0.8782 - precision: 0.9192 - auc: 0.9348 - auc_1: 0.9771 - val_loss: 0.2600 - val_accuracy: 0.8980 - val_precision: 0.9911 - val_auc: 0.9764 - val_auc_1: 0.9927 - lr: 7.8519e-04
Epoch 5/200
54/54 [==============================] - 2s 34ms/step - loss: 0.2413 - accuracy: 0.9065 - precision: 0.9443 - auc: 0.9645 - auc_1: 0.9885 - val_loss: 0.2686 - val_accuracy: 0.8814 - val_precision: 1.0000 - val_auc: 0.9880 - val_auc_1: 0.9964 - lr: 7.8519e-04
Epoch 6/200
54/54 [==============================] - 2s 34ms/step - loss: 0.2140 - accuracy: 0.9276 - precision: 0.9500 - auc: 0.9720 - auc_1: 0.9889 - val_loss: 0.2214 - val_accuracy: 0.9275 - val_precision: 1.0000 - val_auc: 0.9939 - val_auc_1: 0.9982 - lr: 7.8519e-04
Epoch 7/200
54/54 [==============================] - 2s 35ms/step - loss: 0.1836 - accuracy: 0.9376 - precision: 0.9621 - auc: 0.9813 - auc_1: 0.9933 - val_loss: 0.1049 - val_accuracy: 0.9686 - val_precision: 0.9880 - val_auc: 0.9960 - val_auc_1: 0.9988 - lr: 7.8519e-04
Epoch 8/200
54/54 [==============================] - 2s 35ms/step - loss: 0.1742 - accuracy: 0.9435 - precision: 0.9690 - auc: 0.9836 - auc_1: 0.9950 - val_loss: 0.1047 - val_accuracy: 0.9794 - val_precision: 0.9757 - val_auc: 0.9981 - val_auc_1: 0.9994 - lr: 7.8519e-04
Epoch 9/200
54/54 [==============================] - 2s 35ms/step - loss: 0.2112 - accuracy: 0.9288 - precision: 0.9459 - auc: 0.9720 - auc_1: 0.9883 - val_loss: 0.0893 - val_accuracy: 0.9833 - val_precision: 0.9947 - val_auc: 0.9971 - val_auc_1: 0.9992 - lr: 7.8519e-04
Epoch 10/200
54/54 [==============================] - 2s 34ms/step - loss: 0.1518 - accuracy: 0.9565 - precision: 0.9785 - auc: 0.9886 - auc_1: 0.9964 - val_loss: 0.1002 - val_accuracy: 0.9794 - val_precision: 0.9882 - val_auc: 0.9953 - val_auc_1: 0.9977 - lr: 7.8519e-04

[I 2026-03-20 08:18:35,865] Trial 26 finished with value: 0.0 and parameters: {'activation': 'leaky_relu', 'regularizer_value_2': 5.07943460582084e-06, 'N_layers': 18, 'learning_rate': 0.0007851948619875096, 'optimizer': 'adamw', 'N_1st_layer': 165, 'Dropout': 'n', 'N_1_layer': 227, 'Dropout_value_L2': 0.12606169034158268, 'N_2_layer': 203, 'Dropout_value_L3': 0.1321281558038611, 'N_3_layer': 153, 'Dropout_value_L4': 0.1069044016283536, 'N_4_layer': 133, 'Dropout_value_L5': 0.10681554589771765, 'N_5_layer': 245, 'Dropout_value_L6': 0.14906052013769697, 'N_6_layer': 221, 'Dropout_value_L7': 0.1005840918034559, 'N_7_layer': 140, 'Dropout_value_L8': 0.1050614778209614, 'N_8_layer': 225, 'Dropout_value_L9': 0.1063771939075962, 'N_9_layer': 199, 'Dropout_value_L10': 0.1086997655462491, 'N_10_layer': 170, 'Dropout_value_L11': 0.1443406174946664, 'N_11_layer': 161, 'Dropout_value_L12': 0.11282692266635194, 'N_12_layer': 162, 'Dropout_value_L13': 0.11654283782196063, 'N_13_layer': 145, 'Dropout_value_L14': 0.10593549980734727, 'N_14_layer': 197, 'Dropout_value_L15': 0.10603427026370446, 'N_15_layer': 146, 'Dropout_value_L16': 0.10554554170403617, 'N_16_layer': 208, 'Dropout_value_L17': 0.11059139937686083, 'N_17_layer': 147, 'Dropout_value_L18': 0.10865285817534691, 'N_18_layer': 175, 'Dropout_value_L19': 0.13659824277036797}. Best is trial 6 with value: 0.0.

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to
==================================================================================================
 input_1 (InputLayer)        [(None, 12)]                 0         []

 dense (Dense)               (None, 207)                  2691      ['input_1[0][0]']

 activation (Activation)     (None, 207)                  0         ['dense[0][0]']

 batch_normalization (Batch  (None, 207)                  828       ['activation[0][0]']
 Normalization)

 dense_1 (Dense)             (None, 185)                  38480     ['batch_normalization[0][0]']

 batch_normalization_1 (Bat  (None, 185)                  740       ['dense_1[0][0]']
 chNormalization)

 dense_2 (Dense)             (None, 185)                  34410     ['batch_normalization_1[0][0]'
                                                                    ]

 batch_normalization_2 (Bat  (None, 185)                  740       ['dense_2[0][0]']
 chNormalization)

 dense_3 (Dense)             (None, 185)                  38480     ['batch_normalization[0][0]']

 add (Add)                   (None, 185)                  0         ['batch_normalization_2[0][0]'
                                                                    , 'dense_3[0][0]']

 activation_1 (Activation)   (None, 185)                  0         ['add[0][0]']

 dense_4 (Dense)             (None, 242)                  45012     ['activation_1[0][0]']

 batch_normalization_3 (Bat  (None, 242)                  968       ['dense_4[0][0]']
 chNormalization)

 dense_5 (Dense)             (None, 242)                  58806     ['batch_normalization_3[0][0]'
                                                                    ]

 batch_normalization_4 (Bat  (None, 242)                  968       ['dense_5[0][0]']
 chNormalization)

 dense_6 (Dense)             (None, 242)                  45012     ['activation_1[0][0]']

 add_1 (Add)                 (None, 242)                  0         ['batch_normalization_4[0][0]'
                                                                    , 'dense_6[0][0]']

 activation_2 (Activation)   (None, 242)                  0         ['add_1[0][0]']

 dense_7 (Dense)             (None, 198)                  48114     ['activation_2[0][0]']

 batch_normalization_5 (Bat  (None, 198)                  792       ['dense_7[0][0]']
 chNormalization)

 dense_8 (Dense)             (None, 198)                  39402     ['batch_normalization_5[0][0]'
                                                                    ]

 batch_normalization_6 (Bat  (None, 198)                  792       ['dense_8[0][0]']
 chNormalization)

 dense_9 (Dense)             (None, 198)                  48114     ['activation_2[0][0]']

 add_2 (Add)                 (None, 198)                  0         ['batch_normalization_6[0][0]'
                                                                    , 'dense_9[0][0]']

 activation_3 (Activation)   (None, 198)                  0         ['add_2[0][0]']

 dense_10 (Dense)            (None, 171)                  34029     ['activation_3[0][0]']

 batch_normalization_7 (Bat  (None, 171)                  684       ['dense_10[0][0]']
 chNormalization)

 dense_11 (Dense)            (None, 171)                  29412     ['batch_normalization_7[0][0]'
                                                                    ]

 batch_normalization_8 (Bat  (None, 171)                  684       ['dense_11[0][0]']
 chNormalization)

 dense_12 (Dense)            (None, 171)                  34029     ['activation_3[0][0]']

 add_3 (Add)                 (None, 171)                  0         ['batch_normalization_8[0][0]'
                                                                    , 'dense_12[0][0]']

 activation_4 (Activation)   (None, 171)                  0         ['add_3[0][0]']

 dense_13 (Dense)            (None, 256)                  44032     ['activation_4[0][0]']

 batch_normalization_9 (Bat  (None, 256)                  1024      ['dense_13[0][0]']
 chNormalization)

 dense_14 (Dense)            (None, 256)                  65792     ['batch_normalization_9[0][0]'
                                                                    ]

 batch_normalization_10 (Ba  (None, 256)                  1024      ['dense_14[0][0]']
 tchNormalization)

 dense_15 (Dense)            (None, 256)                  44032     ['activation_4[0][0]']

 add_4 (Add)                 (None, 256)                  0         ['batch_normalization_10[0][0]
                                                                    ',
                                                                     'dense_15[0][0]']

 activation_5 (Activation)   (None, 256)                  0         ['add_4[0][0]']

 dense_16 (Dense)            (None, 249)                  63993     ['activation_5[0][0]']

 batch_normalization_11 (Ba  (None, 249)                  996       ['dense_16[0][0]']
 tchNormalization)

 dense_17 (Dense)            (None, 249)                  62250     ['batch_normalization_11[0][0]
                                                                    ']

 batch_normalization_12 (Ba  (None, 249)                  996       ['dense_17[0][0]']
 tchNormalization)

 dense_18 (Dense)            (None, 249)                  63993     ['activation_5[0][0]']

 add_5 (Add)                 (None, 249)                  0         ['batch_normalization_12[0][0]
                                                                    ',
                                                                     'dense_18[0][0]']

 activation_6 (Activation)   (None, 249)                  0         ['add_5[0][0]']

 dense_19 (Dense)            (None, 164)                  41000     ['activation_6[0][0]']

 batch_normalization_13 (Ba  (None, 164)                  656       ['dense_19[0][0]']
 tchNormalization)

 dense_20 (Dense)            (None, 164)                  27060     ['batch_normalization_13[0][0]
                                                                    ']

 batch_normalization_14 (Ba  (None, 164)                  656       ['dense_20[0][0]']
 tchNormalization)

 dense_21 (Dense)            (None, 164)                  41000     ['activation_6[0][0]']

 add_6 (Add)                 (None, 164)                  0         ['batch_normalization_14[0][0]
                                                                    ',
                                                                     'dense_21[0][0]']

 activation_7 (Activation)   (None, 164)                  0         ['add_6[0][0]']

 dense_22 (Dense)            (None, 243)                  40095     ['activation_7[0][0]']

 batch_normalization_15 (Ba  (None, 243)                  972       ['dense_22[0][0]']
 tchNormalization)

 dense_23 (Dense)            (None, 243)                  59292     ['batch_normalization_15[0][0]
                                                                    ']

 batch_normalization_16 (Ba  (None, 243)                  972       ['dense_23[0][0]']
 tchNormalization)

 dense_24 (Dense)            (None, 243)                  40095     ['activation_7[0][0]']

 add_7 (Add)                 (None, 243)                  0         ['batch_normalization_16[0][0]
                                                                    ',
                                                                     'dense_24[0][0]']

 activation_8 (Activation)   (None, 243)                  0         ['add_7[0][0]']

 dense_25 (Dense)            (None, 181)                  44164     ['activation_8[0][0]']

 batch_normalization_17 (Ba  (None, 181)                  724       ['dense_25[0][0]']
 tchNormalization)

 dense_26 (Dense)            (None, 181)                  32942     ['batch_normalization_17[0][0]
                                                                    ']

 batch_normalization_18 (Ba  (None, 181)                  724       ['dense_26[0][0]']
 tchNormalization)

 dense_27 (Dense)            (None, 181)                  44164     ['activation_8[0][0]']

 add_8 (Add)                 (None, 181)                  0         ['batch_normalization_18[0][0]
                                                                    ',
                                                                     'dense_27[0][0]']

 activation_9 (Activation)   (None, 181)                  0         ['add_8[0][0]']

 dense_28 (Dense)            (None, 211)                  38402     ['activation_9[0][0]']

 batch_normalization_19 (Ba  (None, 211)                  844       ['dense_28[0][0]']
 tchNormalization)

 dense_29 (Dense)            (None, 211)                  44732     ['batch_normalization_19[0][0]
                                                                    ']

 batch_normalization_20 (Ba  (None, 211)                  844       ['dense_29[0][0]']
 tchNormalization)

 dense_30 (Dense)            (None, 211)                  38402     ['activation_9[0][0]']

 add_9 (Add)                 (None, 211)                  0         ['batch_normalization_20[0][0]
                                                                    ',
                                                                     'dense_30[0][0]']

 activation_10 (Activation)  (None, 211)                  0         ['add_9[0][0]']

 dense_31 (Dense)            (None, 219)                  46428     ['activation_10[0][0]']

 batch_normalization_21 (Ba  (None, 219)                  876       ['dense_31[0][0]']
 tchNormalization)

 dense_32 (Dense)            (None, 219)                  48180     ['batch_normalization_21[0][0]
                                                                    ']

 batch_normalization_22 (Ba  (None, 219)                  876       ['dense_32[0][0]']
 tchNormalization)

 dense_33 (Dense)            (None, 219)                  46428     ['activation_10[0][0]']

 add_10 (Add)                (None, 219)                  0         ['batch_normalization_22[0][0]
                                                                    ',
                                                                     'dense_33[0][0]']

 activation_11 (Activation)  (None, 219)                  0         ['add_10[0][0]']

 dense_34 (Dense)            (None, 186)                  40920     ['activation_11[0][0]']

 batch_normalization_23 (Ba  (None, 186)                  744       ['dense_34[0][0]']
 tchNormalization)

 dense_35 (Dense)            (None, 186)                  34782     ['batch_normalization_23[0][0]
                                                                    ']

 batch_normalization_24 (Ba  (None, 186)                  744       ['dense_35[0][0]']
 tchNormalization)

 dense_36 (Dense)            (None, 186)                  40920     ['activation_11[0][0]']

 add_11 (Add)                (None, 186)                  0         ['batch_normalization_24[0][0]
                                                                    ',
                                                                     'dense_36[0][0]']

 activation_12 (Activation)  (None, 186)                  0         ['add_11[0][0]']

 dense_37 (Dense)            (None, 144)                  26928     ['activation_12[0][0]']

 batch_normalization_25 (Ba  (None, 144)                  576       ['dense_37[0][0]']
 tchNormalization)

 dense_38 (Dense)            (None, 144)                  20880     ['batch_normalization_25[0][0]
                                                                    ']

 batch_normalization_26 (Ba  (None, 144)                  576       ['dense_38[0][0]']
 tchNormalization)

 dense_39 (Dense)            (None, 144)                  26928     ['activation_12[0][0]']

 add_12 (Add)                (None, 144)                  0         ['batch_normalization_26[0][0]
                                                                    ',
                                                                     'dense_39[0][0]']

 activation_13 (Activation)  (None, 144)                  0         ['add_12[0][0]']

 dense_40 (Dense)            (None, 216)                  31320     ['activation_13[0][0]']

 batch_normalization_27 (Ba  (None, 216)                  864       ['dense_40[0][0]']
 tchNormalization)

 dense_41 (Dense)            (None, 216)                  46872     ['batch_normalization_27[0][0]
                                                                    ']

 batch_normalization_28 (Ba  (None, 216)                  864       ['dense_41[0][0]']
 tchNormalization)

 dense_42 (Dense)            (None, 216)                  31320     ['activation_13[0][0]']

 add_13 (Add)                (None, 216)                  0         ['batch_normalization_28[0][0]
                                                                    ',
                                                                     'dense_42[0][0]']

 activation_14 (Activation)  (None, 216)                  0         ['add_13[0][0]']

 dense_43 (Dense)            (None, 205)                  44485     ['activation_14[0][0]']

 batch_normalization_29 (Ba  (None, 205)                  820       ['dense_43[0][0]']
 tchNormalization)

 dense_44 (Dense)            (None, 205)                  42230     ['batch_normalization_29[0][0]
                                                                    ']

 batch_normalization_30 (Ba  (None, 205)                  820       ['dense_44[0][0]']
 tchNormalization)

 dense_45 (Dense)            (None, 205)                  44485     ['activation_14[0][0]']

 add_14 (Add)                (None, 205)                  0         ['batch_normalization_30[0][0]
                                                                    ',
                                                                     'dense_45[0][0]']

 activation_15 (Activation)  (None, 205)                  0         ['add_14[0][0]']

 dense_46 (Dense)            (None, 182)                  37492     ['activation_15[0][0]']

 batch_normalization_31 (Ba  (None, 182)                  728       ['dense_46[0][0]']
 tchNormalization)

 dense_47 (Dense)            (None, 182)                  33306     ['batch_normalization_31[0][0]
                                                                    ']

 batch_normalization_32 (Ba  (None, 182)                  728       ['dense_47[0][0]']
 tchNormalization)

 dense_48 (Dense)            (None, 182)                  37492     ['activation_15[0][0]']

 add_15 (Add)                (None, 182)                  0         ['batch_normalization_32[0][0]
                                                                    ',
                                                                     'dense_48[0][0]']

 activation_16 (Activation)  (None, 182)                  0         ['add_15[0][0]']

 dense_49 (Dense)            (None, 187)                  34221     ['activation_16[0][0]']

 batch_normalization_33 (Ba  (None, 187)                  748       ['dense_49[0][0]']
 tchNormalization)

 dense_50 (Dense)            (None, 187)                  35156     ['batch_normalization_33[0][0]
                                                                    ']

 batch_normalization_34 (Ba  (None, 187)                  748       ['dense_50[0][0]']
 tchNormalization)

 dense_51 (Dense)            (None, 187)                  34221     ['activation_16[0][0]']

 add_16 (Add)                (None, 187)                  0         ['batch_normalization_34[0][0]
                                                                    ',
                                                                     'dense_51[0][0]']

 activation_17 (Activation)  (None, 187)                  0         ['add_16[0][0]']

 dropout (Dropout)           (None, 187)                  0         ['activation_17[0][0]']

 dense_52 (Dense)            (None, 1)                    188       ['dropout[0][0]']

==================================================================================================
Total params: 2144953 (8.18 MB)
Trainable params: 2130783 (8.13 MB)
Non-trainable params: 14170 (55.35 KB)
__________________________________________________________________________________________________
None
Epoch 1/200
54/54 [==============================] - 22s 51ms/step - loss: 0.5009 - accuracy: 0.7765 - precision: 0.8377 - auc: 0.8087 - auc_1: 0.9227 - val_loss: 0.3612 - val_accuracy: 0.8755 - val_precision: 0.9878 - val_auc: 0.9569 - val_auc_1: 0.9866 - lr: 9.0416e-04
Epoch 2/200
54/54 [==============================] - 2s 34ms/step - loss: 0.3020 - accuracy: 0.8647 - precision: 0.9111 - auc: 0.9310 - auc_1: 0.9766 - val_loss: 0.2466 - val_accuracy: 0.9020 - val_precision: 0.9826 - val_auc: 0.9633 - val_auc_1: 0.9888 - lr: 9.0416e-04
Epoch 3/200
54/54 [==============================] - 2s 33ms/step - loss: 0.2787 - accuracy: 0.8771 - precision: 0.9158 - auc: 0.9393 - auc_1: 0.9787 - val_loss: 0.3188 - val_accuracy: 0.8284 - val_precision: 1.0000 - val_auc: 0.9793 - val_auc_1: 0.9934 - lr: 9.0416e-04
Epoch 4/200
54/54 [==============================] - 2s 34ms/step - loss: 0.2848 - accuracy: 0.8724 - precision: 0.9152 - auc: 0.9365 - auc_1: 0.9766 - val_loss: 0.3965 - val_accuracy: 0.8608 - val_precision: 0.9921 - val_auc: 0.9746 - val_auc_1: 0.9919 - lr: 9.0416e-04
Epoch 5/200
54/54 [==============================] - 2s 36ms/step - loss: 0.2206 - accuracy: 0.9065 - precision: 0.9394 - auc: 0.9616 - auc_1: 0.9874 - val_loss: 0.2891 - val_accuracy: 0.9108 - val_precision: 0.9941 - val_auc: 0.9787 - val_auc_1: 0.9924 - lr: 9.0416e-04
Epoch 6/200
54/54 [==============================] - 2s 39ms/step - loss: 0.3043 - accuracy: 0.8853 - precision: 0.9299 - auc: 0.9355 - auc_1: 0.9745 - val_loss: 0.1957 - val_accuracy: 0.9118 - val_precision: 0.9927 - val_auc: 0.9802 - val_auc_1: 0.9941 - lr: 9.0416e-04
Epoch 7/200
54/54 [==============================] - 2s 40ms/step - loss: 0.1673 - accuracy: 0.9365 - precision: 0.9584 - auc: 0.9778 - auc_1: 0.9932 - val_loss: 0.1332 - val_accuracy: 0.9520 - val_precision: 0.9904 - val_auc: 0.9918 - val_auc_1: 0.9974 - lr: 9.0416e-04
Epoch 8/200
54/54 [==============================] - 2s 44ms/step - loss: 0.1932 - accuracy: 0.9200 - precision: 0.9552 - auc: 0.9698 - auc_1: 0.9901 - val_loss: 0.0821 - val_accuracy: 0.9696 - val_precision: 0.9766 - val_auc: 0.9966 - val_auc_1: 0.9989 - lr: 9.0416e-04
Epoch 9/200
54/54 [==============================] - 2s 40ms/step - loss: 0.1276 - accuracy: 0.9571 - precision: 0.9681 - auc: 0.9866 - auc_1: 0.9947 - val_loss: 0.0838 - val_accuracy: 0.9676 - val_precision: 0.9680 - val_auc: 0.9944 - val_auc_1: 0.9972 - lr: 9.0416e-04
Epoch 10/200
54/54 [==============================] - 2s 36ms/step - loss: 0.1188 - accuracy: 0.9529 - precision: 0.9686 - auc: 0.9883 - auc_1: 0.9957 - val_loss: 0.0749 - val_accuracy: 0.9755 - val_precision: 0.9920 - val_auc: 0.9967 - val_auc_1: 0.9990 - lr: 9.0416e-04
Epoch 11/200
54/54 [==============================] - 2s 34ms/step - loss: 0.0939 - accuracy: 0.9629 - precision: 0.9772 - auc: 0.9935 - auc_1: 0.9979 - val_loss: 0.0607 - val_accuracy: 0.9804 - val_precision: 0.9934 - val_auc: 0.9983 - val_auc_1: 0.9994 - lr: 9.0416e-04
Epoch 12/200
54/54 [==============================] - 2s 37ms/step - loss: 0.1016 - accuracy: 0.9641 - precision: 0.9742 - auc: 0.9906 - auc_1: 0.9960 - val_loss: 0.0398 - val_accuracy: 0.9892 - val_precision: 0.9987 - val_auc: 0.9998 - val_auc_1: 0.9999 - lr: 9.0416e-04
Epoch 13/200
54/54 [==============================] - 2s 40ms/step - loss: 0.0853 - accuracy: 0.9694 - precision: 0.9811 - auc: 0.9942 - auc_1: 0.9982 - val_loss: 0.0226 - val_accuracy: 0.9922 - val_precision: 0.9948 - val_auc: 0.9996 - val_auc_1: 0.9999 - lr: 9.0416e-04
Epoch 14/200

[I 2026-03-20 08:19:39,779] Trial 27 finished with value: 0.00784313678741455 and parameters: {'activation': 'leaky_relu', 'regularizer_value_2': 3.188051732890058e-07, 'N_layers': 17, 'learning_rate': 0.0009041556113593388, 'optimizer': 'adamw', 'N_1st_layer': 207, 'Dropout': 'n', 'N_1_layer': 185, 'Dropout_value_L2': 0.14486623864878756, 'N_2_layer': 242, 'Dropout_value_L3': 0.14233296368056836, 'N_3_layer': 198, 'Dropout_value_L4': 0.11500756817096311, 'N_4_layer': 171, 'Dropout_value_L5': 0.11542976979713451, 'N_5_layer': 256, 'Dropout_value_L6': 0.12554964600194507, 'N_6_layer': 249, 'Dropout_value_L7': 0.11041583900026197, 'N_7_layer': 164, 'Dropout_value_L8': 0.11192703027376764, 'N_8_layer': 243, 'Dropout_value_L9': 0.11669718620260688, 'N_9_layer': 181, 'Dropout_value_L10': 0.11877927780879692, 'N_10_layer': 211, 'Dropout_value_L11': 0.13714168609915348, 'N_11_layer': 219, 'Dropout_value_L12': 0.10654994467135359, 'N_12_layer': 186, 'Dropout_value_L13': 0.10512945283654908, 'N_13_layer': 144, 'Dropout_value_L14': 0.11019439303791288, 'N_14_layer': 216, 'Dropout_value_L15': 0.12419456088022174, 'N_15_layer': 205, 'Dropout_value_L16': 0.11468319361448255, 'N_16_layer': 182, 'Dropout_value_L17': 0.10605196120928947, 'N_17_layer': 187, 'Dropout_value_L18': 0.10182737879557646}. Best is trial 6 with value: 0.0.

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to
==================================================================================================
 input_1 (InputLayer)        [(None, 12)]                 0         []

 dense (Dense)               (None, 187)                  2431      ['input_1[0][0]']

 activation (Activation)     (None, 187)                  0         ['dense[0][0]']

 batch_normalization (Batch  (None, 187)                  748       ['activation[0][0]']
 Normalization)

 dense_1 (Dense)             (None, 200)                  37600     ['batch_normalization[0][0]']

 batch_normalization_1 (Bat  (None, 200)                  800       ['dense_1[0][0]']
 chNormalization)

 dense_2 (Dense)             (None, 200)                  40200     ['batch_normalization_1[0][0]'
                                                                    ]

 batch_normalization_2 (Bat  (None, 200)                  800       ['dense_2[0][0]']
 chNormalization)

 dense_3 (Dense)             (None, 200)                  37600     ['batch_normalization[0][0]']

 add (Add)                   (None, 200)                  0         ['batch_normalization_2[0][0]'
                                                                    , 'dense_3[0][0]']

 activation_1 (Activation)   (None, 200)                  0         ['add[0][0]']

 dense_4 (Dense)             (None, 219)                  44019     ['activation_1[0][0]']

 batch_normalization_3 (Bat  (None, 219)                  876       ['dense_4[0][0]']
 chNormalization)

 dense_5 (Dense)             (None, 219)                  48180     ['batch_normalization_3[0][0]'
                                                                    ]

 batch_normalization_4 (Bat  (None, 219)                  876       ['dense_5[0][0]']
 chNormalization)

 dense_6 (Dense)             (None, 219)                  44019     ['activation_1[0][0]']

 add_1 (Add)                 (None, 219)                  0         ['batch_normalization_4[0][0]'
                                                                    , 'dense_6[0][0]']

 activation_2 (Activation)   (None, 219)                  0         ['add_1[0][0]']

 dense_7 (Dense)             (None, 173)                  38060     ['activation_2[0][0]']

 batch_normalization_5 (Bat  (None, 173)                  692       ['dense_7[0][0]']
 chNormalization)

 dense_8 (Dense)             (None, 173)                  30102     ['batch_normalization_5[0][0]'
                                                                    ]

 batch_normalization_6 (Bat  (None, 173)                  692       ['dense_8[0][0]']
 chNormalization)

 dense_9 (Dense)             (None, 173)                  38060     ['activation_2[0][0]']

 add_2 (Add)                 (None, 173)                  0         ['batch_normalization_6[0][0]'
                                                                    , 'dense_9[0][0]']

 activation_3 (Activation)   (None, 173)                  0         ['add_2[0][0]']

 dense_10 (Dense)            (None, 147)                  25578     ['activation_3[0][0]']

 batch_normalization_7 (Bat  (None, 147)                  588       ['dense_10[0][0]']
 chNormalization)

 dense_11 (Dense)            (None, 147)                  21756     ['batch_normalization_7[0][0]'
                                                                    ]

 batch_normalization_8 (Bat  (None, 147)                  588       ['dense_11[0][0]']
 chNormalization)

 dense_12 (Dense)            (None, 147)                  25578     ['activation_3[0][0]']

 add_3 (Add)                 (None, 147)                  0         ['batch_normalization_8[0][0]'
                                                                    , 'dense_12[0][0]']

 activation_4 (Activation)   (None, 147)                  0         ['add_3[0][0]']

 dense_13 (Dense)            (None, 228)                  33744     ['activation_4[0][0]']

 batch_normalization_9 (Bat  (None, 228)                  912       ['dense_13[0][0]']
 chNormalization)

 dense_14 (Dense)            (None, 228)                  52212     ['batch_normalization_9[0][0]'
                                                                    ]

 batch_normalization_10 (Ba  (None, 228)                  912       ['dense_14[0][0]']
 tchNormalization)

 dense_15 (Dense)            (None, 228)                  33744     ['activation_4[0][0]']

 add_4 (Add)                 (None, 228)                  0         ['batch_normalization_10[0][0]
                                                                    ',
                                                                     'dense_15[0][0]']

 activation_5 (Activation)   (None, 228)                  0         ['add_4[0][0]']

 dense_16 (Dense)            (None, 238)                  54502     ['activation_5[0][0]']

 batch_normalization_11 (Ba  (None, 238)                  952       ['dense_16[0][0]']
 tchNormalization)

 dense_17 (Dense)            (None, 238)                  56882     ['batch_normalization_11[0][0]
                                                                    ']

 batch_normalization_12 (Ba  (None, 238)                  952       ['dense_17[0][0]']
 tchNormalization)

 dense_18 (Dense)            (None, 238)                  54502     ['activation_5[0][0]']

 add_5 (Add)                 (None, 238)                  0         ['batch_normalization_12[0][0]
                                                                    ',
                                                                     'dense_18[0][0]']

 activation_6 (Activation)   (None, 238)                  0         ['add_5[0][0]']

 dense_19 (Dense)            (None, 154)                  36806     ['activation_6[0][0]']

 batch_normalization_13 (Ba  (None, 154)                  616       ['dense_19[0][0]']
 tchNormalization)

 dense_20 (Dense)            (None, 154)                  23870     ['batch_normalization_13[0][0]
                                                                    ']

 batch_normalization_14 (Ba  (None, 154)                  616       ['dense_20[0][0]']
 tchNormalization)

 dense_21 (Dense)            (None, 154)                  36806     ['activation_6[0][0]']

 add_6 (Add)                 (None, 154)                  0         ['batch_normalization_14[0][0]
                                                                    ',
                                                                     'dense_21[0][0]']

 activation_7 (Activation)   (None, 154)                  0         ['add_6[0][0]']

 dense_22 (Dense)            (None, 207)                  32085     ['activation_7[0][0]']

 batch_normalization_15 (Ba  (None, 207)                  828       ['dense_22[0][0]']
 tchNormalization)

 dense_23 (Dense)            (None, 207)                  43056     ['batch_normalization_15[0][0]
                                                                    ']

 batch_normalization_16 (Ba  (None, 207)                  828       ['dense_23[0][0]']
 tchNormalization)

 dense_24 (Dense)            (None, 207)                  32085     ['activation_7[0][0]']

 add_7 (Add)                 (None, 207)                  0         ['batch_normalization_16[0][0]
                                                                    ',
                                                                     'dense_24[0][0]']

 activation_8 (Activation)   (None, 207)                  0         ['add_7[0][0]']

 dense_25 (Dense)            (None, 159)                  33072     ['activation_8[0][0]']

 batch_normalization_17 (Ba  (None, 159)                  636       ['dense_25[0][0]']
 tchNormalization)

 dense_26 (Dense)            (None, 159)                  25440     ['batch_normalization_17[0][0]
                                                                    ']

 batch_normalization_18 (Ba  (None, 159)                  636       ['dense_26[0][0]']
 tchNormalization)

 dense_27 (Dense)            (None, 159)                  33072     ['activation_8[0][0]']

 add_8 (Add)                 (None, 159)                  0         ['batch_normalization_18[0][0]
                                                                    ',
                                                                     'dense_27[0][0]']

 activation_9 (Activation)   (None, 159)                  0         ['add_8[0][0]']

 dense_28 (Dense)            (None, 196)                  31360     ['activation_9[0][0]']

 batch_normalization_19 (Ba  (None, 196)                  784       ['dense_28[0][0]']
 tchNormalization)

 dense_29 (Dense)            (None, 196)                  38612     ['batch_normalization_19[0][0]
                                                                    ']

 batch_normalization_20 (Ba  (None, 196)                  784       ['dense_29[0][0]']
 tchNormalization)

 dense_30 (Dense)            (None, 196)                  31360     ['activation_9[0][0]']

 add_9 (Add)                 (None, 196)                  0         ['batch_normalization_20[0][0]
                                                                    ',
                                                                     'dense_30[0][0]']

 activation_10 (Activation)  (None, 196)                  0         ['add_9[0][0]']

 dense_31 (Dense)            (None, 185)                  36445     ['activation_10[0][0]']

 batch_normalization_21 (Ba  (None, 185)                  740       ['dense_31[0][0]']
 tchNormalization)

 dense_32 (Dense)            (None, 185)                  34410     ['batch_normalization_21[0][0]
                                                                    ']

 batch_normalization_22 (Ba  (None, 185)                  740       ['dense_32[0][0]']
 tchNormalization)

 dense_33 (Dense)            (None, 185)                  36445     ['activation_10[0][0]']

 add_10 (Add)                (None, 185)                  0         ['batch_normalization_22[0][0]
                                                                    ',
                                                                     'dense_33[0][0]']

 activation_11 (Activation)  (None, 185)                  0         ['add_10[0][0]']

 dense_34 (Dense)            (None, 143)                  26598     ['activation_11[0][0]']

 batch_normalization_23 (Ba  (None, 143)                  572       ['dense_34[0][0]']
 tchNormalization)

 dense_35 (Dense)            (None, 143)                  20592     ['batch_normalization_23[0][0]
                                                                    ']

 batch_normalization_24 (Ba  (None, 143)                  572       ['dense_35[0][0]']
 tchNormalization)

 dense_36 (Dense)            (None, 143)                  26598     ['activation_11[0][0]']

 add_11 (Add)                (None, 143)                  0         ['batch_normalization_24[0][0]
                                                                    ',
                                                                     'dense_36[0][0]']

 activation_12 (Activation)  (None, 143)                  0         ['add_11[0][0]']

 dense_37 (Dense)            (None, 160)                  23040     ['activation_12[0][0]']

 batch_normalization_25 (Ba  (None, 160)                  640       ['dense_37[0][0]']
 tchNormalization)

 dense_38 (Dense)            (None, 160)                  25760     ['batch_normalization_25[0][0]
                                                                    ']

 batch_normalization_26 (Ba  (None, 160)                  640       ['dense_38[0][0]']
 tchNormalization)

 dense_39 (Dense)            (None, 160)                  23040     ['activation_12[0][0]']

 add_12 (Add)                (None, 160)                  0         ['batch_normalization_26[0][0]
                                                                    ',
                                                                     'dense_39[0][0]']

 activation_13 (Activation)  (None, 160)                  0         ['add_12[0][0]']

 dense_40 (Dense)            (None, 197)                  31717     ['activation_13[0][0]']

 batch_normalization_27 (Ba  (None, 197)                  788       ['dense_40[0][0]']
 tchNormalization)

 dense_41 (Dense)            (None, 197)                  39006     ['batch_normalization_27[0][0]
                                                                    ']

 batch_normalization_28 (Ba  (None, 197)                  788       ['dense_41[0][0]']
 tchNormalization)

 dense_42 (Dense)            (None, 197)                  31717     ['activation_13[0][0]']

 add_13 (Add)                (None, 197)                  0         ['batch_normalization_28[0][0]
                                                                    ',
                                                                     'dense_42[0][0]']

 activation_14 (Activation)  (None, 197)                  0         ['add_13[0][0]']

 dense_43 (Dense)            (None, 128)                  25344     ['activation_14[0][0]']

 batch_normalization_29 (Ba  (None, 128)                  512       ['dense_43[0][0]']
 tchNormalization)

 dense_44 (Dense)            (None, 128)                  16512     ['batch_normalization_29[0][0]
                                                                    ']

 batch_normalization_30 (Ba  (None, 128)                  512       ['dense_44[0][0]']
 tchNormalization)

 dense_45 (Dense)            (None, 128)                  25344     ['activation_14[0][0]']

 add_14 (Add)                (None, 128)                  0         ['batch_normalization_30[0][0]
                                                                    ',
                                                                     'dense_45[0][0]']

 activation_15 (Activation)  (None, 128)                  0         ['add_14[0][0]']

 dense_46 (Dense)            (None, 230)                  29670     ['activation_15[0][0]']

 batch_normalization_31 (Ba  (None, 230)                  920       ['dense_46[0][0]']
 tchNormalization)

 dense_47 (Dense)            (None, 230)                  53130     ['batch_normalization_31[0][0]
                                                                    ']

 batch_normalization_32 (Ba  (None, 230)                  920       ['dense_47[0][0]']
 tchNormalization)

 dense_48 (Dense)            (None, 230)                  29670     ['activation_15[0][0]']

 add_15 (Add)                (None, 230)                  0         ['batch_normalization_32[0][0]
                                                                    ',
                                                                     'dense_48[0][0]']

 activation_16 (Activation)  (None, 230)                  0         ['add_15[0][0]']

 dropout (Dropout)           (None, 230)                  0         ['activation_16[0][0]']

 dense_49 (Dense)            (None, 1)                    231       ['dropout[0][0]']

==================================================================================================
Total params: 1676122 (6.39 MB)
Trainable params: 1663892 (6.35 MB)
Non-trainable params: 12230 (47.77 KB)
__________________________________________________________________________________________________
None
Epoch 1/200
54/54 [==============================] - 15s 45ms/step - loss: 0.5220 - accuracy: 0.7976 - precision: 0.8589 - auc: 0.8265 - auc_1: 0.9288 - val_loss: 0.3346 - val_accuracy: 0.8755 - val_precision: 0.9334 - val_auc: 0.9350 - val_auc_1: 0.9789 - lr: 7.3870e-04
Epoch 2/200
54/54 [==============================] - 1s 27ms/step - loss: 0.3334 - accuracy: 0.8576 - precision: 0.9038 - auc: 0.9204 - auc_1: 0.9704 - val_loss: 0.2744 - val_accuracy: 0.8941 - val_precision: 0.9339 - val_auc: 0.9526 - val_auc_1: 0.9851 - lr: 7.3870e-04
Epoch 3/200
54/54 [==============================] - 1s 27ms/step - loss: 0.2653 - accuracy: 0.9000 - precision: 0.9361 - auc: 0.9520 - auc_1: 0.9801 - val_loss: 0.3232 - val_accuracy: 0.9382 - val_precision: 0.9594 - val_auc: 0.9647 - val_auc_1: 0.9813 - lr: 7.3870e-04
Epoch 4/200
54/54 [==============================] - 1s 28ms/step - loss: 0.1967 - accuracy: 0.9200 - precision: 0.9502 - auc: 0.9721 - auc_1: 0.9902 - val_loss: 0.2104 - val_accuracy: 0.9402 - val_precision: 0.9972 - val_auc: 0.9881 - val_auc_1: 0.9966 - lr: 7.3870e-04
Epoch 5/200
54/54 [==============================] - 1s 27ms/step - loss: 0.2011 - accuracy: 0.9453 - precision: 0.9596 - auc: 0.9795 - auc_1: 0.9920 - val_loss: 0.2163 - val_accuracy: 0.9765 - val_precision: 0.9805 - val_auc: 0.9921 - val_auc_1: 0.9953 - lr: 7.3870e-04
Epoch 6/200
54/54 [==============================] - 1s 27ms/step - loss: 0.1880 - accuracy: 0.9435 - precision: 0.9609 - auc: 0.9737 - auc_1: 0.9875 - val_loss: 0.1626 - val_accuracy: 0.9657 - val_precision: 0.9959 - val_auc: 0.9932 - val_auc_1: 0.9980 - lr: 7.3870e-04
Epoch 7/200
54/54 [==============================] - 1s 27ms/step - loss: 0.1135 - accuracy: 0.9671 - precision: 0.9758 - auc: 0.9899 - auc_1: 0.9961 - val_loss: 0.0634 - val_accuracy: 0.9755 - val_precision: 0.9947 - val_auc: 0.9983 - val_auc_1: 0.9995 - lr: 7.3870e-04
Epoch 8/200
54/54 [==============================] - 1s 26ms/step - loss: 0.1187 - accuracy: 0.9694 - precision: 0.9804 - auc: 0.9873 - auc_1: 0.9934 - val_loss: 0.2575 - val_accuracy: 0.8304 - val_precision: 0.8156 - val_auc: 0.9961 - val_auc_1: 0.9979 - lr: 7.3870e-04
Epoch 9/200
54/54 [==============================] - 1s 26ms/step - loss: 0.1202 - accuracy: 0.9676 - precision: 0.9766 - auc: 0.9874 - auc_1: 0.9948 - val_loss: 0.3486 - val_accuracy: 0.7500 - val_precision: 0.7500 - val_auc: 0.9988 - val_auc_1: 0.9996 - lr: 7.3870e-04
Epoch 10/200
54/54 [==============================] - 1s 27ms/step - loss: 0.0895 - accuracy: 0.9700 - precision: 0.9819 - auc: 0.9948 - auc_1: 0.9983 - val_loss: 0.1384 - val_accuracy: 0.9676 - val_precision: 0.9867 - val_auc: 0.9865 - val_auc_1: 0.9946 - lr: 7.3870e-04
Epoch 11/200
54/54 [==============================] - 1s 27ms/step - loss: 0.0857 - accuracy: 0.9759 - precision: 0.9820 - auc: 0.9919 - auc_1: 0.9955 - val_loss: 0.0464 - val_accuracy: 0.9941 - val_precision: 0.9922 - val_auc: 0.9960 - val_auc_1: 0.9973 - lr: 7.3870e-04
Epoch 12/200
54/54 [==============================] - 1s 26ms/step - loss: 0.0796 - accuracy: 0.9824 - precision: 0.9882 - auc: 0.9942 - auc_1: 0.9971 - val_loss: 0.0878 - val_accuracy: 0.9853 - val_precision: 0.9870 - val_auc: 0.9930 - val_auc_1: 0.9956 - lr: 7.3870e-04
Epoch 13/200
54/54 [==============================] - 1s 27ms/step - loss: 0.1027 - accuracy: 0.9694 - precision: 0.9774 - auc: 0.9918 - auc_1: 0.9966 - val_loss: 0.1960 - val_accuracy: 0.9216 - val_precision: 0.9053 - val_auc: 0.9964 - val_auc_1: 0.9981 - lr: 7.3870e-04
Epoch 14/200
54/54 [==============================] - 1s 26ms/step - loss: 0.0641 - accuracy: 0.9765 - precision: 0.9858 - auc: 0.9976 - auc_1: 0.9992 - val_loss: 0.0407 - val_accuracy: 0.9863 - val_precision: 0.9858 - val_auc: 0.9996 - val_auc_1: 0.9999 - lr: 7.3870e-04
Epoch 15/200
54/54 [==============================] - 1s 27ms/step - loss: 0.0772 - accuracy: 0.9765 - precision: 0.9843 - auc: 0.9952 - auc_1: 0.9981 - val_loss: 0.0635 - val_accuracy: 0.9922 - val_precision: 1.0000 - val_auc: 0.9973 - val_auc_1: 0.9993 - lr: 7.3870e-04
Epoch 16/200
54/54 [==============================] - 1s 26ms/step - loss: 0.0747 - accuracy: 0.9824 - precision: 0.9859 - auc: 0.9935 - auc_1: 0.9971 - val_loss: 0.0316 - val_accuracy: 0.9931 - val_precision: 0.9987 - val_auc: 0.9993 - val_auc_1: 0.9998 - lr: 7.3870e-04
Epoch 17/200

[I 2026-03-20 08:20:23,588] Trial 28 finished with value: 0.005882382392883301 and parameters: {'activation': 'leaky_relu', 'regularizer_value_2': 1.676327652681954e-06, 'N_layers': 16, 'learning_rate': 0.0007387045989280765, 'optimizer': 'rmsprop', 'N_1st_layer': 187, 'Dropout': 'n', 'N_1_layer': 200, 'Dropout_value_L2': 0.10652030373871087, 'N_2_layer': 219, 'Dropout_value_L3': 0.14443806076473084, 'N_3_layer': 173, 'Dropout_value_L4': 0.10714643051530512, 'N_4_layer': 147, 'Dropout_value_L5': 0.10314213048281885, 'N_5_layer': 228, 'Dropout_value_L6': 0.1315465757726461, 'N_6_layer': 238, 'Dropout_value_L7': 0.12136894286440561, 'N_7_layer': 154, 'Dropout_value_L8': 0.11730600858681418, 'N_8_layer': 207, 'Dropout_value_L9': 0.12153914919619987, 'N_9_layer': 159, 'Dropout_value_L10': 0.11256199267841119, 'N_10_layer': 196, 'Dropout_value_L11': 0.14301682289384343, 'N_11_layer': 185, 'Dropout_value_L12': 0.12539902671198908, 'N_12_layer': 143, 'Dropout_value_L13': 0.11767720866770594, 'N_13_layer': 160, 'Dropout_value_L14': 0.11390064960716773, 'N_14_layer': 197, 'Dropout_value_L15': 0.1412934240713419, 'N_15_layer': 128, 'Dropout_value_L16': 0.11927384120827404, 'N_16_layer': 230, 'Dropout_value_L17': 0.11506958140887638}. Best is trial 6 with value: 0.0.

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to
==================================================================================================
 input_1 (InputLayer)        [(None, 12)]                 0         []

 dense (Dense)               (None, 247)                  3211      ['input_1[0][0]']

 activation (Activation)     (None, 247)                  0         ['dense[0][0]']

 batch_normalization (Batch  (None, 247)                  988       ['activation[0][0]']
 Normalization)

 dense_1 (Dense)             (None, 237)                  58776     ['batch_normalization[0][0]']

 batch_normalization_1 (Bat  (None, 237)                  948       ['dense_1[0][0]']
 chNormalization)

 dropout (Dropout)           (None, 237)                  0         ['batch_normalization_1[0][0]'
                                                                    ]

 dense_2 (Dense)             (None, 237)                  56406     ['dropout[0][0]']

 batch_normalization_2 (Bat  (None, 237)                  948       ['dense_2[0][0]']
 chNormalization)

 dense_3 (Dense)             (None, 237)                  58776     ['batch_normalization[0][0]']

 add (Add)                   (None, 237)                  0         ['batch_normalization_2[0][0]'
                                                                    , 'dense_3[0][0]']

 activation_1 (Activation)   (None, 237)                  0         ['add[0][0]']

 dense_4 (Dense)             (None, 179)                  42602     ['activation_1[0][0]']

 batch_normalization_3 (Bat  (None, 179)                  716       ['dense_4[0][0]']
 chNormalization)

 dropout_1 (Dropout)         (None, 179)                  0         ['batch_normalization_3[0][0]'
                                                                    ]

 dense_5 (Dense)             (None, 179)                  32220     ['dropout_1[0][0]']

 batch_normalization_4 (Bat  (None, 179)                  716       ['dense_5[0][0]']
 chNormalization)

 dense_6 (Dense)             (None, 179)                  42602     ['activation_1[0][0]']

 add_1 (Add)                 (None, 179)                  0         ['batch_normalization_4[0][0]'
                                                                    , 'dense_6[0][0]']

 activation_2 (Activation)   (None, 179)                  0         ['add_1[0][0]']

 dense_7 (Dense)             (None, 131)                  23580     ['activation_2[0][0]']

 batch_normalization_5 (Bat  (None, 131)                  524       ['dense_7[0][0]']
 chNormalization)

 dropout_2 (Dropout)         (None, 131)                  0         ['batch_normalization_5[0][0]'
                                                                    ]

 dense_8 (Dense)             (None, 131)                  17292     ['dropout_2[0][0]']

 batch_normalization_6 (Bat  (None, 131)                  524       ['dense_8[0][0]']
 chNormalization)

 dense_9 (Dense)             (None, 131)                  23580     ['activation_2[0][0]']

 add_2 (Add)                 (None, 131)                  0         ['batch_normalization_6[0][0]'
                                                                    , 'dense_9[0][0]']

 activation_3 (Activation)   (None, 131)                  0         ['add_2[0][0]']

 dense_10 (Dense)            (None, 162)                  21384     ['activation_3[0][0]']

 batch_normalization_7 (Bat  (None, 162)                  648       ['dense_10[0][0]']
 chNormalization)

 dropout_3 (Dropout)         (None, 162)                  0         ['batch_normalization_7[0][0]'
                                                                    ]

 dense_11 (Dense)            (None, 162)                  26406     ['dropout_3[0][0]']

 batch_normalization_8 (Bat  (None, 162)                  648       ['dense_11[0][0]']
 chNormalization)

 dense_12 (Dense)            (None, 162)                  21384     ['activation_3[0][0]']

 add_3 (Add)                 (None, 162)                  0         ['batch_normalization_8[0][0]'
                                                                    , 'dense_12[0][0]']

 activation_4 (Activation)   (None, 162)                  0         ['add_3[0][0]']

 dense_13 (Dense)            (None, 245)                  39935     ['activation_4[0][0]']

 batch_normalization_9 (Bat  (None, 245)                  980       ['dense_13[0][0]']
 chNormalization)

 dropout_4 (Dropout)         (None, 245)                  0         ['batch_normalization_9[0][0]'
                                                                    ]

 dense_14 (Dense)            (None, 245)                  60270     ['dropout_4[0][0]']

 batch_normalization_10 (Ba  (None, 245)                  980       ['dense_14[0][0]']
 tchNormalization)

 dense_15 (Dense)            (None, 245)                  39935     ['activation_4[0][0]']

 add_4 (Add)                 (None, 245)                  0         ['batch_normalization_10[0][0]
                                                                    ',
                                                                     'dense_15[0][0]']

 activation_5 (Activation)   (None, 245)                  0         ['add_4[0][0]']

 dense_16 (Dense)            (None, 162)                  39852     ['activation_5[0][0]']

 batch_normalization_11 (Ba  (None, 162)                  648       ['dense_16[0][0]']
 tchNormalization)

 dropout_5 (Dropout)         (None, 162)                  0         ['batch_normalization_11[0][0]
                                                                    ']

 dense_17 (Dense)            (None, 162)                  26406     ['dropout_5[0][0]']

 batch_normalization_12 (Ba  (None, 162)                  648       ['dense_17[0][0]']
 tchNormalization)

 dense_18 (Dense)            (None, 162)                  39852     ['activation_5[0][0]']

 add_5 (Add)                 (None, 162)                  0         ['batch_normalization_12[0][0]
                                                                    ',
                                                                     'dense_18[0][0]']

 activation_6 (Activation)   (None, 162)                  0         ['add_5[0][0]']

 dense_19 (Dense)            (None, 137)                  22331     ['activation_6[0][0]']

 batch_normalization_13 (Ba  (None, 137)                  548       ['dense_19[0][0]']
 tchNormalization)

 dropout_6 (Dropout)         (None, 137)                  0         ['batch_normalization_13[0][0]
                                                                    ']

 dense_20 (Dense)            (None, 137)                  18906     ['dropout_6[0][0]']

 batch_normalization_14 (Ba  (None, 137)                  548       ['dense_20[0][0]']
 tchNormalization)

 dense_21 (Dense)            (None, 137)                  22331     ['activation_6[0][0]']

 add_6 (Add)                 (None, 137)                  0         ['batch_normalization_14[0][0]
                                                                    ',
                                                                     'dense_21[0][0]']

 activation_7 (Activation)   (None, 137)                  0         ['add_6[0][0]']

 dense_22 (Dense)            (None, 182)                  25116     ['activation_7[0][0]']

 batch_normalization_15 (Ba  (None, 182)                  728       ['dense_22[0][0]']
 tchNormalization)

 dropout_7 (Dropout)         (None, 182)                  0         ['batch_normalization_15[0][0]
                                                                    ']

 dense_23 (Dense)            (None, 182)                  33306     ['dropout_7[0][0]']

 batch_normalization_16 (Ba  (None, 182)                  728       ['dense_23[0][0]']
 tchNormalization)

 dense_24 (Dense)            (None, 182)                  25116     ['activation_7[0][0]']

 add_7 (Add)                 (None, 182)                  0         ['batch_normalization_16[0][0]
                                                                    ',
                                                                     'dense_24[0][0]']

 activation_8 (Activation)   (None, 182)                  0         ['add_7[0][0]']

 dense_25 (Dense)            (None, 165)                  30195     ['activation_8[0][0]']

 batch_normalization_17 (Ba  (None, 165)                  660       ['dense_25[0][0]']
 tchNormalization)

 dropout_8 (Dropout)         (None, 165)                  0         ['batch_normalization_17[0][0]
                                                                    ']

 dense_26 (Dense)            (None, 165)                  27390     ['dropout_8[0][0]']

 batch_normalization_18 (Ba  (None, 165)                  660       ['dense_26[0][0]']
 tchNormalization)

 dense_27 (Dense)            (None, 165)                  30195     ['activation_8[0][0]']

 add_8 (Add)                 (None, 165)                  0         ['batch_normalization_18[0][0]
                                                                    ',
                                                                     'dense_27[0][0]']

 activation_9 (Activation)   (None, 165)                  0         ['add_8[0][0]']

 dense_28 (Dense)            (None, 142)                  23572     ['activation_9[0][0]']

 batch_normalization_19 (Ba  (None, 142)                  568       ['dense_28[0][0]']
 tchNormalization)

 dropout_9 (Dropout)         (None, 142)                  0         ['batch_normalization_19[0][0]
                                                                    ']

 dense_29 (Dense)            (None, 142)                  20306     ['dropout_9[0][0]']

 batch_normalization_20 (Ba  (None, 142)                  568       ['dense_29[0][0]']
 tchNormalization)

 dense_30 (Dense)            (None, 142)                  23572     ['activation_9[0][0]']

 add_9 (Add)                 (None, 142)                  0         ['batch_normalization_20[0][0]
                                                                    ',
                                                                     'dense_30[0][0]']

 activation_10 (Activation)  (None, 142)                  0         ['add_9[0][0]']

 dense_31 (Dense)            (None, 202)                  28886     ['activation_10[0][0]']

 batch_normalization_21 (Ba  (None, 202)                  808       ['dense_31[0][0]']
 tchNormalization)

 dropout_10 (Dropout)        (None, 202)                  0         ['batch_normalization_21[0][0]
                                                                    ']

 dense_32 (Dense)            (None, 202)                  41006     ['dropout_10[0][0]']

 batch_normalization_22 (Ba  (None, 202)                  808       ['dense_32[0][0]']
 tchNormalization)

 dense_33 (Dense)            (None, 202)                  28886     ['activation_10[0][0]']

 add_10 (Add)                (None, 202)                  0         ['batch_normalization_22[0][0]
                                                                    ',
                                                                     'dense_33[0][0]']

 activation_11 (Activation)  (None, 202)                  0         ['add_10[0][0]']

 dense_34 (Dense)            (None, 239)                  48517     ['activation_11[0][0]']

 batch_normalization_23 (Ba  (None, 239)                  956       ['dense_34[0][0]']
 tchNormalization)

 dropout_11 (Dropout)        (None, 239)                  0         ['batch_normalization_23[0][0]
                                                                    ']

 dense_35 (Dense)            (None, 239)                  57360     ['dropout_11[0][0]']

 batch_normalization_24 (Ba  (None, 239)                  956       ['dense_35[0][0]']
 tchNormalization)

 dense_36 (Dense)            (None, 239)                  48517     ['activation_11[0][0]']

 add_11 (Add)                (None, 239)                  0         ['batch_normalization_24[0][0]
                                                                    ',
                                                                     'dense_36[0][0]']

 activation_12 (Activation)  (None, 239)                  0         ['add_11[0][0]']

 dense_37 (Dense)            (None, 224)                  53760     ['activation_12[0][0]']

 batch_normalization_25 (Ba  (None, 224)                  896       ['dense_37[0][0]']
 tchNormalization)

 dropout_12 (Dropout)        (None, 224)                  0         ['batch_normalization_25[0][0]
                                                                    ']

 dense_38 (Dense)            (None, 224)                  50400     ['dropout_12[0][0]']

 batch_normalization_26 (Ba  (None, 224)                  896       ['dense_38[0][0]']
 tchNormalization)

 dense_39 (Dense)            (None, 224)                  53760     ['activation_12[0][0]']

 add_12 (Add)                (None, 224)                  0         ['batch_normalization_26[0][0]
                                                                    ',
                                                                     'dense_39[0][0]']

 activation_13 (Activation)  (None, 224)                  0         ['add_12[0][0]']

 dense_40 (Dense)            (None, 180)                  40500     ['activation_13[0][0]']

 batch_normalization_27 (Ba  (None, 180)                  720       ['dense_40[0][0]']
 tchNormalization)

 dropout_13 (Dropout)        (None, 180)                  0         ['batch_normalization_27[0][0]
                                                                    ']

 dense_41 (Dense)            (None, 180)                  32580     ['dropout_13[0][0]']

 batch_normalization_28 (Ba  (None, 180)                  720       ['dense_41[0][0]']
 tchNormalization)

 dense_42 (Dense)            (None, 180)                  40500     ['activation_13[0][0]']

 add_13 (Add)                (None, 180)                  0         ['batch_normalization_28[0][0]
                                                                    ',
                                                                     'dense_42[0][0]']

 activation_14 (Activation)  (None, 180)                  0         ['add_13[0][0]']

 dense_43 (Dense)            (None, 180)                  32580     ['activation_14[0][0]']

 batch_normalization_29 (Ba  (None, 180)                  720       ['dense_43[0][0]']
 tchNormalization)

 dropout_14 (Dropout)        (None, 180)                  0         ['batch_normalization_29[0][0]
                                                                    ']

 dense_44 (Dense)            (None, 180)                  32580     ['dropout_14[0][0]']

 batch_normalization_30 (Ba  (None, 180)                  720       ['dense_44[0][0]']
 tchNormalization)

 dense_45 (Dense)            (None, 180)                  32580     ['activation_14[0][0]']

 add_14 (Add)                (None, 180)                  0         ['batch_normalization_30[0][0]
                                                                    ',
                                                                     'dense_45[0][0]']

 activation_15 (Activation)  (None, 180)                  0         ['add_14[0][0]']

 dense_46 (Dense)            (None, 203)                  36743     ['activation_15[0][0]']

 batch_normalization_31 (Ba  (None, 203)                  812       ['dense_46[0][0]']
 tchNormalization)

 dropout_15 (Dropout)        (None, 203)                  0         ['batch_normalization_31[0][0]
                                                                    ']

 dense_47 (Dense)            (None, 203)                  41412     ['dropout_15[0][0]']

 batch_normalization_32 (Ba  (None, 203)                  812       ['dense_47[0][0]']
 tchNormalization)

 dense_48 (Dense)            (None, 203)                  36743     ['activation_15[0][0]']

 add_15 (Add)                (None, 203)                  0         ['batch_normalization_32[0][0]
                                                                    ',
                                                                     'dense_48[0][0]']

 activation_16 (Activation)  (None, 203)                  0         ['add_15[0][0]']

 dense_49 (Dense)            (None, 144)                  29376     ['activation_16[0][0]']

 batch_normalization_33 (Ba  (None, 144)                  576       ['dense_49[0][0]']
 tchNormalization)

 dropout_16 (Dropout)        (None, 144)                  0         ['batch_normalization_33[0][0]
                                                                    ']

 dense_50 (Dense)            (None, 144)                  20880     ['dropout_16[0][0]']

 batch_normalization_34 (Ba  (None, 144)                  576       ['dense_50[0][0]']
 tchNormalization)

 dense_51 (Dense)            (None, 144)                  29376     ['activation_16[0][0]']

 add_16 (Add)                (None, 144)                  0         ['batch_normalization_34[0][0]
                                                                    ',
                                                                     'dense_51[0][0]']

 activation_17 (Activation)  (None, 144)                  0         ['add_16[0][0]']

 dense_52 (Dense)            (None, 156)                  22620     ['activation_17[0][0]']

 batch_normalization_35 (Ba  (None, 156)                  624       ['dense_52[0][0]']
 tchNormalization)

 dropout_17 (Dropout)        (None, 156)                  0         ['batch_normalization_35[0][0]
                                                                    ']

 dense_53 (Dense)            (None, 156)                  24492     ['dropout_17[0][0]']

 batch_normalization_36 (Ba  (None, 156)                  624       ['dense_53[0][0]']
 tchNormalization)

 dense_54 (Dense)            (None, 156)                  22620     ['activation_17[0][0]']

 add_17 (Add)                (None, 156)                  0         ['batch_normalization_36[0][0]
                                                                    ',
                                                                     'dense_54[0][0]']

 activation_18 (Activation)  (None, 156)                  0         ['add_17[0][0]']

 dropout_18 (Dropout)        (None, 156)                  0         ['activation_18[0][0]']

 dense_55 (Dense)            (None, 1)                    157       ['dropout_18[0][0]']

==================================================================================================
Total params: 1890784 (7.21 MB)
Trainable params: 1877210 (7.16 MB)
Non-trainable params: 13574 (53.02 KB)
__________________________________________________________________________________________________
None
Epoch 1/200
54/54 [==============================] - 17s 49ms/step - loss: 0.6929 - accuracy: 0.7224 - precision: 0.7878 - auc: 0.6356 - auc_1: 0.8280 - val_loss: 0.5745 - val_accuracy: 0.7510 - val_precision: 0.7507 - val_auc: 0.7787 - val_auc_1: 0.9136 - lr: 5.6356e-04
Epoch 2/200
54/54 [==============================] - 2s 31ms/step - loss: 0.5006 - accuracy: 0.7953 - precision: 0.8411 - auc: 0.8148 - auc_1: 0.9229 - val_loss: 0.5159 - val_accuracy: 0.8039 - val_precision: 0.9435 - val_auc: 0.8883 - val_auc_1: 0.9591 - lr: 5.6356e-04
Epoch 3/200
54/54 [==============================] - 2s 31ms/step - loss: 0.3841 - accuracy: 0.8347 - precision: 0.8817 - auc: 0.8988 - auc_1: 0.9641 - val_loss: 0.4542 - val_accuracy: 0.8294 - val_precision: 0.9511 - val_auc: 0.9216 - val_auc_1: 0.9746 - lr: 5.6356e-04
Epoch 4/200
54/54 [==============================] - 2s 31ms/step - loss: 0.3494 - accuracy: 0.8618 - precision: 0.9025 - auc: 0.9218 - auc_1: 0.9719 - val_loss: 0.4687 - val_accuracy: 0.8725 - val_precision: 0.9635 - val_auc: 0.9206 - val_auc_1: 0.9579 - lr: 5.6356e-04
Epoch 5/200

[I 2026-03-20 08:21:32,435] Trial 29 finished with value: 0.0 and parameters: {'activation': 'leaky_relu', 'regularizer_value_2': 3.9156177140347715e-06, 'N_layers': 18, 'learning_rate': 0.0005635582885589742, 'optimizer': 'rmsprop', 'N_1st_layer': 247, 'Dropout': 'y', 'N_1_layer': 237, 'Dropout_value_L2': 0.11220963051182621, 'N_2_layer': 179, 'Dropout_value_L3': 0.1388143031761599, 'N_3_layer': 131, 'Dropout_value_L4': 0.12346717845090936, 'N_4_layer': 162, 'Dropout_value_L5': 0.10993540478637547, 'N_5_layer': 245, 'Dropout_value_L6': 0.10375460805218457, 'N_6_layer': 162, 'Dropout_value_L7': 0.1289303295322945, 'N_7_layer': 137, 'Dropout_value_L8': 0.10277135610680949, 'N_8_layer': 182, 'Dropout_value_L9': 0.1111773494308261, 'N_9_layer': 165, 'Dropout_value_L10': 0.13535218741546845, 'N_10_layer': 142, 'Dropout_value_L11': 0.13148254652538802, 'N_11_layer': 202, 'Dropout_value_L12': 0.11788832771213263, 'N_12_layer': 239, 'Dropout_value_L13': 0.10417914313689432, 'N_13_layer': 224, 'Dropout_value_L14': 0.12209978986231612, 'N_14_layer': 180, 'Dropout_value_L15': 0.10901096663615917, 'N_15_layer': 180, 'Dropout_value_L16': 0.10730867671965692, 'N_16_layer': 203, 'Dropout_value_L17': 0.12519474392723684, 'N_17_layer': 144, 'Dropout_value_L18': 0.10963887758757523, 'N_18_layer': 156, 'Dropout_value_L19': 0.12742536303429025}. Best is trial 6 with value: 0.0.

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to
==================================================================================================
 input_1 (InputLayer)        [(None, 12)]                 0         []

 dense (Dense)               (None, 226)                  2938      ['input_1[0][0]']

 activation (Activation)     (None, 226)                  0         ['dense[0][0]']

 batch_normalization (Batch  (None, 226)                  904       ['activation[0][0]']
 Normalization)

 dense_1 (Dense)             (None, 141)                  32007     ['batch_normalization[0][0]']

 batch_normalization_1 (Bat  (None, 141)                  564       ['dense_1[0][0]']
 chNormalization)

 dense_2 (Dense)             (None, 141)                  20022     ['batch_normalization_1[0][0]'
                                                                    ]

 batch_normalization_2 (Bat  (None, 141)                  564       ['dense_2[0][0]']
 chNormalization)

 dense_3 (Dense)             (None, 141)                  32007     ['batch_normalization[0][0]']

 add (Add)                   (None, 141)                  0         ['batch_normalization_2[0][0]'
                                                                    , 'dense_3[0][0]']

 activation_1 (Activation)   (None, 141)                  0         ['add[0][0]']

 dense_4 (Dense)             (None, 164)                  23288     ['activation_1[0][0]']

 batch_normalization_3 (Bat  (None, 164)                  656       ['dense_4[0][0]']
 chNormalization)

 dense_5 (Dense)             (None, 164)                  27060     ['batch_normalization_3[0][0]'
                                                                    ]

 batch_normalization_4 (Bat  (None, 164)                  656       ['dense_5[0][0]']
 chNormalization)

 dense_6 (Dense)             (None, 164)                  23288     ['activation_1[0][0]']

 add_1 (Add)                 (None, 164)                  0         ['batch_normalization_4[0][0]'
                                                                    , 'dense_6[0][0]']

 activation_2 (Activation)   (None, 164)                  0         ['add_1[0][0]']

 dense_7 (Dense)             (None, 149)                  24585     ['activation_2[0][0]']

 batch_normalization_5 (Bat  (None, 149)                  596       ['dense_7[0][0]']
 chNormalization)

 dense_8 (Dense)             (None, 149)                  22350     ['batch_normalization_5[0][0]'
                                                                    ]

 batch_normalization_6 (Bat  (None, 149)                  596       ['dense_8[0][0]']
 chNormalization)

 dense_9 (Dense)             (None, 149)                  24585     ['activation_2[0][0]']

 add_2 (Add)                 (None, 149)                  0         ['batch_normalization_6[0][0]'
                                                                    , 'dense_9[0][0]']

 activation_3 (Activation)   (None, 149)                  0         ['add_2[0][0]']

 dense_10 (Dense)            (None, 180)                  27000     ['activation_3[0][0]']

 batch_normalization_7 (Bat  (None, 180)                  720       ['dense_10[0][0]']
 chNormalization)

 dense_11 (Dense)            (None, 180)                  32580     ['batch_normalization_7[0][0]'
                                                                    ]

 batch_normalization_8 (Bat  (None, 180)                  720       ['dense_11[0][0]']
 chNormalization)

 dense_12 (Dense)            (None, 180)                  27000     ['activation_3[0][0]']

 add_3 (Add)                 (None, 180)                  0         ['batch_normalization_8[0][0]'
                                                                    , 'dense_12[0][0]']

 activation_4 (Activation)   (None, 180)                  0         ['add_3[0][0]']

 dense_13 (Dense)            (None, 228)                  41268     ['activation_4[0][0]']

 batch_normalization_9 (Bat  (None, 228)                  912       ['dense_13[0][0]']
 chNormalization)

 dense_14 (Dense)            (None, 228)                  52212     ['batch_normalization_9[0][0]'
                                                                    ]

 batch_normalization_10 (Ba  (None, 228)                  912       ['dense_14[0][0]']
 tchNormalization)

 dense_15 (Dense)            (None, 228)                  41268     ['activation_4[0][0]']

 add_4 (Add)                 (None, 228)                  0         ['batch_normalization_10[0][0]
                                                                    ',
                                                                     'dense_15[0][0]']

 activation_5 (Activation)   (None, 228)                  0         ['add_4[0][0]']

 dense_16 (Dense)            (None, 203)                  46487     ['activation_5[0][0]']

 batch_normalization_11 (Ba  (None, 203)                  812       ['dense_16[0][0]']
 tchNormalization)

 dense_17 (Dense)            (None, 203)                  41412     ['batch_normalization_11[0][0]
                                                                    ']

 batch_normalization_12 (Ba  (None, 203)                  812       ['dense_17[0][0]']
 tchNormalization)

 dense_18 (Dense)            (None, 203)                  46487     ['activation_5[0][0]']

 add_5 (Add)                 (None, 203)                  0         ['batch_normalization_12[0][0]
                                                                    ',
                                                                     'dense_18[0][0]']

 activation_6 (Activation)   (None, 203)                  0         ['add_5[0][0]']

 dense_19 (Dense)            (None, 185)                  37740     ['activation_6[0][0]']

 batch_normalization_13 (Ba  (None, 185)                  740       ['dense_19[0][0]']
 tchNormalization)

 dense_20 (Dense)            (None, 185)                  34410     ['batch_normalization_13[0][0]
                                                                    ']

 batch_normalization_14 (Ba  (None, 185)                  740       ['dense_20[0][0]']
 tchNormalization)

 dense_21 (Dense)            (None, 185)                  37740     ['activation_6[0][0]']

 add_6 (Add)                 (None, 185)                  0         ['batch_normalization_14[0][0]
                                                                    ',
                                                                     'dense_21[0][0]']

 activation_7 (Activation)   (None, 185)                  0         ['add_6[0][0]']

 dense_22 (Dense)            (None, 158)                  29388     ['activation_7[0][0]']

 batch_normalization_15 (Ba  (None, 158)                  632       ['dense_22[0][0]']
 tchNormalization)

 dense_23 (Dense)            (None, 158)                  25122     ['batch_normalization_15[0][0]
                                                                    ']

 batch_normalization_16 (Ba  (None, 158)                  632       ['dense_23[0][0]']
 tchNormalization)

 dense_24 (Dense)            (None, 158)                  29388     ['activation_7[0][0]']

 add_7 (Add)                 (None, 158)                  0         ['batch_normalization_16[0][0]
                                                                    ',
                                                                     'dense_24[0][0]']

 activation_8 (Activation)   (None, 158)                  0         ['add_7[0][0]']

 dense_25 (Dense)            (None, 146)                  23214     ['activation_8[0][0]']

 batch_normalization_17 (Ba  (None, 146)                  584       ['dense_25[0][0]']
 tchNormalization)

 dense_26 (Dense)            (None, 146)                  21462     ['batch_normalization_17[0][0]
                                                                    ']

 batch_normalization_18 (Ba  (None, 146)                  584       ['dense_26[0][0]']
 tchNormalization)

 dense_27 (Dense)            (None, 146)                  23214     ['activation_8[0][0]']

 add_8 (Add)                 (None, 146)                  0         ['batch_normalization_18[0][0]
                                                                    ',
                                                                     'dense_27[0][0]']

 activation_9 (Activation)   (None, 146)                  0         ['add_8[0][0]']

 dense_28 (Dense)            (None, 180)                  26460     ['activation_9[0][0]']

 batch_normalization_19 (Ba  (None, 180)                  720       ['dense_28[0][0]']
 tchNormalization)

 dense_29 (Dense)            (None, 180)                  32580     ['batch_normalization_19[0][0]
                                                                    ']

 batch_normalization_20 (Ba  (None, 180)                  720       ['dense_29[0][0]']
 tchNormalization)

 dense_30 (Dense)            (None, 180)                  26460     ['activation_9[0][0]']

 add_9 (Add)                 (None, 180)                  0         ['batch_normalization_20[0][0]
                                                                    ',
                                                                     'dense_30[0][0]']

 activation_10 (Activation)  (None, 180)                  0         ['add_9[0][0]']

 dense_31 (Dense)            (None, 212)                  38372     ['activation_10[0][0]']

 batch_normalization_21 (Ba  (None, 212)                  848       ['dense_31[0][0]']
 tchNormalization)

 dense_32 (Dense)            (None, 212)                  45156     ['batch_normalization_21[0][0]
                                                                    ']

 batch_normalization_22 (Ba  (None, 212)                  848       ['dense_32[0][0]']
 tchNormalization)

 dense_33 (Dense)            (None, 212)                  38372     ['activation_10[0][0]']

 add_10 (Add)                (None, 212)                  0         ['batch_normalization_22[0][0]
                                                                    ',
                                                                     'dense_33[0][0]']

 activation_11 (Activation)  (None, 212)                  0         ['add_10[0][0]']

 dense_34 (Dense)            (None, 138)                  29394     ['activation_11[0][0]']

 batch_normalization_23 (Ba  (None, 138)                  552       ['dense_34[0][0]']
 tchNormalization)

 dense_35 (Dense)            (None, 138)                  19182     ['batch_normalization_23[0][0]
                                                                    ']

 batch_normalization_24 (Ba  (None, 138)                  552       ['dense_35[0][0]']
 tchNormalization)

 dense_36 (Dense)            (None, 138)                  29394     ['activation_11[0][0]']

 add_11 (Add)                (None, 138)                  0         ['batch_normalization_24[0][0]
                                                                    ',
                                                                     'dense_36[0][0]']

 activation_12 (Activation)  (None, 138)                  0         ['add_11[0][0]']

 dense_37 (Dense)            (None, 136)                  18904     ['activation_12[0][0]']

 batch_normalization_25 (Ba  (None, 136)                  544       ['dense_37[0][0]']
 tchNormalization)

 dense_38 (Dense)            (None, 136)                  18632     ['batch_normalization_25[0][0]
                                                                    ']

 batch_normalization_26 (Ba  (None, 136)                  544       ['dense_38[0][0]']
 tchNormalization)

 dense_39 (Dense)            (None, 136)                  18904     ['activation_12[0][0]']

 add_12 (Add)                (None, 136)                  0         ['batch_normalization_26[0][0]
                                                                    ',
                                                                     'dense_39[0][0]']

 activation_13 (Activation)  (None, 136)                  0         ['add_12[0][0]']

 dense_40 (Dense)            (None, 237)                  32469     ['activation_13[0][0]']

 batch_normalization_27 (Ba  (None, 237)                  948       ['dense_40[0][0]']
 tchNormalization)

 dense_41 (Dense)            (None, 237)                  56406     ['batch_normalization_27[0][0]
                                                                    ']

 batch_normalization_28 (Ba  (None, 237)                  948       ['dense_41[0][0]']
 tchNormalization)

 dense_42 (Dense)            (None, 237)                  32469     ['activation_13[0][0]']

 add_13 (Add)                (None, 237)                  0         ['batch_normalization_28[0][0]
                                                                    ',
                                                                     'dense_42[0][0]']

 activation_14 (Activation)  (None, 237)                  0         ['add_13[0][0]']

 dense_43 (Dense)            (None, 139)                  33082     ['activation_14[0][0]']

 batch_normalization_29 (Ba  (None, 139)                  556       ['dense_43[0][0]']
 tchNormalization)

 dense_44 (Dense)            (None, 139)                  19460     ['batch_normalization_29[0][0]
                                                                    ']

 batch_normalization_30 (Ba  (None, 139)                  556       ['dense_44[0][0]']
 tchNormalization)

 dense_45 (Dense)            (None, 139)                  33082     ['activation_14[0][0]']

 add_14 (Add)                (None, 139)                  0         ['batch_normalization_30[0][0]
                                                                    ',
                                                                     'dense_45[0][0]']

 activation_15 (Activation)  (None, 139)                  0         ['add_14[0][0]']

 dense_46 (Dense)            (None, 187)                  26180     ['activation_15[0][0]']

 batch_normalization_31 (Ba  (None, 187)                  748       ['dense_46[0][0]']
 tchNormalization)

 dense_47 (Dense)            (None, 187)                  35156     ['batch_normalization_31[0][0]
                                                                    ']

 batch_normalization_32 (Ba  (None, 187)                  748       ['dense_47[0][0]']
 tchNormalization)

 dense_48 (Dense)            (None, 187)                  26180     ['activation_15[0][0]']

 add_15 (Add)                (None, 187)                  0         ['batch_normalization_32[0][0]
                                                                    ',
                                                                     'dense_48[0][0]']

 activation_16 (Activation)  (None, 187)                  0         ['add_15[0][0]']

 dense_49 (Dense)            (None, 172)                  32336     ['activation_16[0][0]']

 batch_normalization_33 (Ba  (None, 172)                  688       ['dense_49[0][0]']
 tchNormalization)

 dense_50 (Dense)            (None, 172)                  29756     ['batch_normalization_33[0][0]
                                                                    ']

 batch_normalization_34 (Ba  (None, 172)                  688       ['dense_50[0][0]']
 tchNormalization)

 dense_51 (Dense)            (None, 172)                  32336     ['activation_16[0][0]']

 add_16 (Add)                (None, 172)                  0         ['batch_normalization_34[0][0]
                                                                    ',
                                                                     'dense_51[0][0]']

 activation_17 (Activation)  (None, 172)                  0         ['add_16[0][0]']

 dropout (Dropout)           (None, 172)                  0         ['activation_17[0][0]']

 dense_52 (Dense)            (None, 1)                    173       ['dropout[0][0]']

==================================================================================================
Total params: 1604961 (6.12 MB)
Trainable params: 1592689 (6.08 MB)
Non-trainable params: 12272 (47.94 KB)
__________________________________________________________________________________________________
None
Epoch 1/200
54/54 [==============================] - 22s 51ms/step - loss: 0.6349 - accuracy: 0.7524 - precision: 0.8220 - auc: 0.7538 - auc_1: 0.8979 - val_loss: 0.5402 - val_accuracy: 0.7647 - val_precision: 0.7644 - val_auc: 0.8828 - val_auc_1: 0.9588 - lr: 6.3311e-04
Epoch 2/200
54/54 [==============================] - 2s 33ms/step - loss: 0.4343 - accuracy: 0.8318 - precision: 0.8891 - auc: 0.8869 - auc_1: 0.9575 - val_loss: 0.4018 - val_accuracy: 0.8078 - val_precision: 0.8049 - val_auc: 0.9402 - val_auc_1: 0.9801 - lr: 6.3311e-04
Epoch 3/200
54/54 [==============================] - 2s 33ms/step - loss: 0.3362 - accuracy: 0.8624 - precision: 0.9019 - auc: 0.9319 - auc_1: 0.9771 - val_loss: 0.3001 - val_accuracy: 0.8941 - val_precision: 0.9660 - val_auc: 0.9572 - val_auc_1: 0.9869 - lr: 6.3311e-04
Epoch 4/200
54/54 [==============================] - 2s 33ms/step - loss: 0.3434 - accuracy: 0.8665 - precision: 0.9219 - auc: 0.9259 - auc_1: 0.9733 - val_loss: 0.2963 - val_accuracy: 0.8873 - val_precision: 0.9697 - val_auc: 0.9590 - val_auc_1: 0.9861 - lr: 6.3311e-04
Epoch 5/200
54/54 [==============================] - 2s 33ms/step - loss: 0.3444 - accuracy: 0.8776 - precision: 0.9237 - auc: 0.9307 - auc_1: 0.9731 - val_loss: 0.2803 - val_accuracy: 0.8971 - val_precision: 0.9797 - val_auc: 0.9687 - val_auc_1: 0.9900 - lr: 6.3311e-04
Epoch 6/200
54/54 [==============================] - 2s 32ms/step - loss: 0.2720 - accuracy: 0.9088 - precision: 0.9423 - auc: 0.9559 - auc_1: 0.9841 - val_loss: 0.2997 - val_accuracy: 0.8765 - val_precision: 0.9863 - val_auc: 0.9761 - val_auc_1: 0.9907 - lr: 6.3311e-04
Epoch 7/200
54/54 [==============================] - 2s 32ms/step - loss: 0.3184 - accuracy: 0.8671 - precision: 0.9101 - auc: 0.9348 - auc_1: 0.9777 - val_loss: 0.3341 - val_accuracy: 0.8775 - val_precision: 0.9893 - val_auc: 0.9745 - val_auc_1: 0.9895 - lr: 6.3311e-04
Epoch 8/200
54/54 [==============================] - 2s 33ms/step - loss: 0.2219 - accuracy: 0.9159 - precision: 0.9471 - auc: 0.9731 - auc_1: 0.9914 - val_loss: 0.1269 - val_accuracy: 0.9706 - val_precision: 0.9804 - val_auc: 0.9946 - val_auc_1: 0.9983 - lr: 6.3311e-04
Epoch 9/200
54/54 [==============================] - 2s 33ms/step - loss: 0.1939 - accuracy: 0.9329 - precision: 0.9525 - auc: 0.9806 - auc_1: 0.9933 - val_loss: 0.1205 - val_accuracy: 0.9696 - val_precision: 0.9973 - val_auc: 0.9976 - val_auc_1: 0.9993 - lr: 6.3311e-04
Epoch 10/200
54/54 [==============================] - 2s 34ms/step - loss: 0.1863 - accuracy: 0.9488 - precision: 0.9633 - auc: 0.9814 - auc_1: 0.9932 - val_loss: 0.1018 - val_accuracy: 0.9853 - val_precision: 0.9960 - val_auc: 0.9984 - val_auc_1: 0.9995 - lr: 6.3311e-04
Epoch 11/200
54/54 [==============================] - 2s 34ms/step - loss: 0.1859 - accuracy: 0.9394 - precision: 0.9621 - auc: 0.9824 - auc_1: 0.9932 - val_loss: 0.1255 - val_accuracy: 0.9647 - val_precision: 0.9893 - val_auc: 0.9948 - val_auc_1: 0.9974 - lr: 6.3311e-04
Epoch 12/200
54/54 [==============================] - 2s 33ms/step - loss: 0.1587 - accuracy: 0.9512 - precision: 0.9656 - auc: 0.9886 - auc_1: 0.9959 - val_loss: 0.0798 - val_accuracy: 0.9853 - val_precision: 1.0000 - val_auc: 0.9995 - val_auc_1: 0.9999 - lr: 6.3311e-04
Epoch 13/200
54/54 [==============================] - 2s 34ms/step - loss: 0.1798 - accuracy: 0.9447 - precision: 0.9653 - auc: 0.9826 - auc_1: 0.9934 - val_loss: 0.1087 - val_accuracy: 0.9794 - val_precision: 0.9819 - val_auc: 0.9989 - val_auc_1: 0.9996 - lr: 6.3311e-04
Epoch 14/200

[I 2026-03-20 08:22:46,294] Trial 30 finished with value: 0.0 and parameters: {'activation': 'leaky_relu', 'regularizer_value_2': 6.882307824100193e-06, 'N_layers': 17, 'learning_rate': 0.0006331128316787533, 'optimizer': 'adamw', 'N_1st_layer': 226, 'Dropout': 'n', 'N_1_layer': 141, 'Dropout_value_L2': 0.1298039257068876, 'N_2_layer': 164, 'Dropout_value_L3': 0.12377792767450743, 'N_3_layer': 149, 'Dropout_value_L4': 0.13086389220586656, 'N_4_layer': 180, 'Dropout_value_L5': 0.1407853081691064, 'N_5_layer': 228, 'Dropout_value_L6': 0.14916893211131277, 'N_6_layer': 203, 'Dropout_value_L7': 0.10692601817352457, 'N_7_layer': 185, 'Dropout_value_L8': 0.10760462793516538, 'N_8_layer': 158, 'Dropout_value_L9': 0.1062732120661408, 'N_9_layer': 146, 'Dropout_value_L10': 0.12843709936288872, 'N_10_layer': 180, 'Dropout_value_L11': 0.1496367809388913, 'N_11_layer': 212, 'Dropout_value_L12': 0.1332070350186622, 'N_12_layer': 138, 'Dropout_value_L13': 0.10998661492911979, 'N_13_layer': 136, 'Dropout_value_L14': 0.11917503586193612, 'N_14_layer': 237, 'Dropout_value_L15': 0.1156475341894214, 'N_15_layer': 139, 'Dropout_value_L16': 0.14272224891944166, 'N_16_layer': 187, 'Dropout_value_L17': 0.13022836687824574, 'N_17_layer': 172, 'Dropout_value_L18': 0.13865759208838294}. Best is trial 6 with value: 0.0.

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to
==================================================================================================
 input_1 (InputLayer)        [(None, 12)]                 0         []

 dense (Dense)               (None, 204)                  2652      ['input_1[0][0]']

 activation (Activation)     (None, 204)                  0         ['dense[0][0]']

 batch_normalization (Batch  (None, 204)                  816       ['activation[0][0]']
 Normalization)

 dense_1 (Dense)             (None, 222)                  45510     ['batch_normalization[0][0]']

 batch_normalization_1 (Bat  (None, 222)                  888       ['dense_1[0][0]']
 chNormalization)

 dropout (Dropout)           (None, 222)                  0         ['batch_normalization_1[0][0]'
                                                                    ]

 dense_2 (Dense)             (None, 222)                  49506     ['dropout[0][0]']

 batch_normalization_2 (Bat  (None, 222)                  888       ['dense_2[0][0]']
 chNormalization)

 dense_3 (Dense)             (None, 222)                  45510     ['batch_normalization[0][0]']

 add (Add)                   (None, 222)                  0         ['batch_normalization_2[0][0]'
                                                                    , 'dense_3[0][0]']

 activation_1 (Activation)   (None, 222)                  0         ['add[0][0]']

 dense_4 (Dense)             (None, 201)                  44823     ['activation_1[0][0]']

 batch_normalization_3 (Bat  (None, 201)                  804       ['dense_4[0][0]']
 chNormalization)

 dropout_1 (Dropout)         (None, 201)                  0         ['batch_normalization_3[0][0]'
                                                                    ]

 dense_5 (Dense)             (None, 201)                  40602     ['dropout_1[0][0]']

 batch_normalization_4 (Bat  (None, 201)                  804       ['dense_5[0][0]']
 chNormalization)

 dense_6 (Dense)             (None, 201)                  44823     ['activation_1[0][0]']

 add_1 (Add)                 (None, 201)                  0         ['batch_normalization_4[0][0]'
                                                                    , 'dense_6[0][0]']

 activation_2 (Activation)   (None, 201)                  0         ['add_1[0][0]']

 dense_7 (Dense)             (None, 165)                  33330     ['activation_2[0][0]']

 batch_normalization_5 (Bat  (None, 165)                  660       ['dense_7[0][0]']
 chNormalization)

 dropout_2 (Dropout)         (None, 165)                  0         ['batch_normalization_5[0][0]'
                                                                    ]

 dense_8 (Dense)             (None, 165)                  27390     ['dropout_2[0][0]']

 batch_normalization_6 (Bat  (None, 165)                  660       ['dense_8[0][0]']
 chNormalization)

 dense_9 (Dense)             (None, 165)                  33330     ['activation_2[0][0]']

 add_2 (Add)                 (None, 165)                  0         ['batch_normalization_6[0][0]'
                                                                    , 'dense_9[0][0]']

 activation_3 (Activation)   (None, 165)                  0         ['add_2[0][0]']

 dense_10 (Dense)            (None, 202)                  33532     ['activation_3[0][0]']

 batch_normalization_7 (Bat  (None, 202)                  808       ['dense_10[0][0]']
 chNormalization)

 dropout_3 (Dropout)         (None, 202)                  0         ['batch_normalization_7[0][0]'
                                                                    ]

 dense_11 (Dense)            (None, 202)                  41006     ['dropout_3[0][0]']

 batch_normalization_8 (Bat  (None, 202)                  808       ['dense_11[0][0]']
 chNormalization)

 dense_12 (Dense)            (None, 202)                  33532     ['activation_3[0][0]']

 add_3 (Add)                 (None, 202)                  0         ['batch_normalization_8[0][0]'
                                                                    , 'dense_12[0][0]']

 activation_4 (Activation)   (None, 202)                  0         ['add_3[0][0]']

 dense_13 (Dense)            (None, 241)                  48923     ['activation_4[0][0]']

 batch_normalization_9 (Bat  (None, 241)                  964       ['dense_13[0][0]']
 chNormalization)

 dropout_4 (Dropout)         (None, 241)                  0         ['batch_normalization_9[0][0]'
                                                                    ]

 dense_14 (Dense)            (None, 241)                  58322     ['dropout_4[0][0]']

 batch_normalization_10 (Ba  (None, 241)                  964       ['dense_14[0][0]']
 tchNormalization)

 dense_15 (Dense)            (None, 241)                  48923     ['activation_4[0][0]']

 add_4 (Add)                 (None, 241)                  0         ['batch_normalization_10[0][0]
                                                                    ',
                                                                     'dense_15[0][0]']

 activation_5 (Activation)   (None, 241)                  0         ['add_4[0][0]']

 dense_16 (Dense)            (None, 181)                  43802     ['activation_5[0][0]']

 batch_normalization_11 (Ba  (None, 181)                  724       ['dense_16[0][0]']
 tchNormalization)

 dropout_5 (Dropout)         (None, 181)                  0         ['batch_normalization_11[0][0]
                                                                    ']

 dense_17 (Dense)            (None, 181)                  32942     ['dropout_5[0][0]']

 batch_normalization_12 (Ba  (None, 181)                  724       ['dense_17[0][0]']
 tchNormalization)

 dense_18 (Dense)            (None, 181)                  43802     ['activation_5[0][0]']

 add_5 (Add)                 (None, 181)                  0         ['batch_normalization_12[0][0]
                                                                    ',
                                                                     'dense_18[0][0]']

 activation_6 (Activation)   (None, 181)                  0         ['add_5[0][0]']

 dense_19 (Dense)            (None, 151)                  27482     ['activation_6[0][0]']

 batch_normalization_13 (Ba  (None, 151)                  604       ['dense_19[0][0]']
 tchNormalization)

 dropout_6 (Dropout)         (None, 151)                  0         ['batch_normalization_13[0][0]
                                                                    ']

 dense_20 (Dense)            (None, 151)                  22952     ['dropout_6[0][0]']

 batch_normalization_14 (Ba  (None, 151)                  604       ['dense_20[0][0]']
 tchNormalization)

 dense_21 (Dense)            (None, 151)                  27482     ['activation_6[0][0]']

 add_6 (Add)                 (None, 151)                  0         ['batch_normalization_14[0][0]
                                                                    ',
                                                                     'dense_21[0][0]']

 activation_7 (Activation)   (None, 151)                  0         ['add_6[0][0]']

 dense_22 (Dense)            (None, 202)                  30704     ['activation_7[0][0]']

 batch_normalization_15 (Ba  (None, 202)                  808       ['dense_22[0][0]']
 tchNormalization)

 dropout_7 (Dropout)         (None, 202)                  0         ['batch_normalization_15[0][0]
                                                                    ']

 dense_23 (Dense)            (None, 202)                  41006     ['dropout_7[0][0]']

 batch_normalization_16 (Ba  (None, 202)                  808       ['dense_23[0][0]']
 tchNormalization)

 dense_24 (Dense)            (None, 202)                  30704     ['activation_7[0][0]']

 add_7 (Add)                 (None, 202)                  0         ['batch_normalization_16[0][0]
                                                                    ',
                                                                     'dense_24[0][0]']

 activation_8 (Activation)   (None, 202)                  0         ['add_7[0][0]']

 dense_25 (Dense)            (None, 223)                  45269     ['activation_8[0][0]']

 batch_normalization_17 (Ba  (None, 223)                  892       ['dense_25[0][0]']
 tchNormalization)

 dropout_8 (Dropout)         (None, 223)                  0         ['batch_normalization_17[0][0]
                                                                    ']

 dense_26 (Dense)            (None, 223)                  49952     ['dropout_8[0][0]']

 batch_normalization_18 (Ba  (None, 223)                  892       ['dense_26[0][0]']
 tchNormalization)

 dense_27 (Dense)            (None, 223)                  45269     ['activation_8[0][0]']

 add_8 (Add)                 (None, 223)                  0         ['batch_normalization_18[0][0]
                                                                    ',
                                                                     'dense_27[0][0]']

 activation_9 (Activation)   (None, 223)                  0         ['add_8[0][0]']

 dense_28 (Dense)            (None, 164)                  36736     ['activation_9[0][0]']

 batch_normalization_19 (Ba  (None, 164)                  656       ['dense_28[0][0]']
 tchNormalization)

 dropout_9 (Dropout)         (None, 164)                  0         ['batch_normalization_19[0][0]
                                                                    ']

 dense_29 (Dense)            (None, 164)                  27060     ['dropout_9[0][0]']

 batch_normalization_20 (Ba  (None, 164)                  656       ['dense_29[0][0]']
 tchNormalization)

 dense_30 (Dense)            (None, 164)                  36736     ['activation_9[0][0]']

 add_9 (Add)                 (None, 164)                  0         ['batch_normalization_20[0][0]
                                                                    ',
                                                                     'dense_30[0][0]']

 activation_10 (Activation)  (None, 164)                  0         ['add_9[0][0]']

 dense_31 (Dense)            (None, 192)                  31680     ['activation_10[0][0]']

 batch_normalization_21 (Ba  (None, 192)                  768       ['dense_31[0][0]']
 tchNormalization)

 dropout_10 (Dropout)        (None, 192)                  0         ['batch_normalization_21[0][0]
                                                                    ']

 dense_32 (Dense)            (None, 192)                  37056     ['dropout_10[0][0]']

 batch_normalization_22 (Ba  (None, 192)                  768       ['dense_32[0][0]']
 tchNormalization)

 dense_33 (Dense)            (None, 192)                  31680     ['activation_10[0][0]']

 add_10 (Add)                (None, 192)                  0         ['batch_normalization_22[0][0]
                                                                    ',
                                                                     'dense_33[0][0]']

 activation_11 (Activation)  (None, 192)                  0         ['add_10[0][0]']

 dense_34 (Dense)            (None, 158)                  30494     ['activation_11[0][0]']

 batch_normalization_23 (Ba  (None, 158)                  632       ['dense_34[0][0]']
 tchNormalization)

 dropout_11 (Dropout)        (None, 158)                  0         ['batch_normalization_23[0][0]
                                                                    ']

 dense_35 (Dense)            (None, 158)                  25122     ['dropout_11[0][0]']

 batch_normalization_24 (Ba  (None, 158)                  632       ['dense_35[0][0]']
 tchNormalization)

 dense_36 (Dense)            (None, 158)                  30494     ['activation_11[0][0]']

 add_11 (Add)                (None, 158)                  0         ['batch_normalization_24[0][0]
                                                                    ',
                                                                     'dense_36[0][0]']

 activation_12 (Activation)  (None, 158)                  0         ['add_11[0][0]']

 dense_37 (Dense)            (None, 167)                  26553     ['activation_12[0][0]']

 batch_normalization_25 (Ba  (None, 167)                  668       ['dense_37[0][0]']
 tchNormalization)

 dropout_12 (Dropout)        (None, 167)                  0         ['batch_normalization_25[0][0]
                                                                    ']

 dense_38 (Dense)            (None, 167)                  28056     ['dropout_12[0][0]']

 batch_normalization_26 (Ba  (None, 167)                  668       ['dense_38[0][0]']
 tchNormalization)

 dense_39 (Dense)            (None, 167)                  26553     ['activation_12[0][0]']

 add_12 (Add)                (None, 167)                  0         ['batch_normalization_26[0][0]
                                                                    ',
                                                                     'dense_39[0][0]']

 activation_13 (Activation)  (None, 167)                  0         ['add_12[0][0]']

 dense_40 (Dense)            (None, 222)                  37296     ['activation_13[0][0]']

 batch_normalization_27 (Ba  (None, 222)                  888       ['dense_40[0][0]']
 tchNormalization)

 dropout_13 (Dropout)        (None, 222)                  0         ['batch_normalization_27[0][0]
                                                                    ']

 dense_41 (Dense)            (None, 222)                  49506     ['dropout_13[0][0]']

 batch_normalization_28 (Ba  (None, 222)                  888       ['dense_41[0][0]']
 tchNormalization)

 dense_42 (Dense)            (None, 222)                  37296     ['activation_13[0][0]']

 add_13 (Add)                (None, 222)                  0         ['batch_normalization_28[0][0]
                                                                    ',
                                                                     'dense_42[0][0]']

 activation_14 (Activation)  (None, 222)                  0         ['add_13[0][0]']

 dense_43 (Dense)            (None, 166)                  37018     ['activation_14[0][0]']

 batch_normalization_29 (Ba  (None, 166)                  664       ['dense_43[0][0]']
 tchNormalization)

 dropout_14 (Dropout)        (None, 166)                  0         ['batch_normalization_29[0][0]
                                                                    ']

 dense_44 (Dense)            (None, 166)                  27722     ['dropout_14[0][0]']

 batch_normalization_30 (Ba  (None, 166)                  664       ['dense_44[0][0]']
 tchNormalization)

 dense_45 (Dense)            (None, 166)                  37018     ['activation_14[0][0]']

 add_14 (Add)                (None, 166)                  0         ['batch_normalization_30[0][0]
                                                                    ',
                                                                     'dense_45[0][0]']

 activation_15 (Activation)  (None, 166)                  0         ['add_14[0][0]']

 dense_46 (Dense)            (None, 167)                  27889     ['activation_15[0][0]']

 batch_normalization_31 (Ba  (None, 167)                  668       ['dense_46[0][0]']
 tchNormalization)

 dropout_15 (Dropout)        (None, 167)                  0         ['batch_normalization_31[0][0]
                                                                    ']

 dense_47 (Dense)            (None, 167)                  28056     ['dropout_15[0][0]']

 batch_normalization_32 (Ba  (None, 167)                  668       ['dense_47[0][0]']
 tchNormalization)

 dense_48 (Dense)            (None, 167)                  27889     ['activation_15[0][0]']

 add_15 (Add)                (None, 167)                  0         ['batch_normalization_32[0][0]
                                                                    ',
                                                                     'dense_48[0][0]']

 activation_16 (Activation)  (None, 167)                  0         ['add_15[0][0]']

 dense_49 (Dense)            (None, 196)                  32928     ['activation_16[0][0]']

 batch_normalization_33 (Ba  (None, 196)                  784       ['dense_49[0][0]']
 tchNormalization)

 dropout_16 (Dropout)        (None, 196)                  0         ['batch_normalization_33[0][0]
                                                                    ']

 dense_50 (Dense)            (None, 196)                  38612     ['dropout_16[0][0]']

 batch_normalization_34 (Ba  (None, 196)                  784       ['dense_50[0][0]']
 tchNormalization)

 dense_51 (Dense)            (None, 196)                  32928     ['activation_16[0][0]']

 add_16 (Add)                (None, 196)                  0         ['batch_normalization_34[0][0]
                                                                    ',
                                                                     'dense_51[0][0]']

 activation_17 (Activation)  (None, 196)                  0         ['add_16[0][0]']

 dense_52 (Dense)            (None, 184)                  36248     ['activation_17[0][0]']

 batch_normalization_35 (Ba  (None, 184)                  736       ['dense_52[0][0]']
 tchNormalization)

 dropout_17 (Dropout)        (None, 184)                  0         ['batch_normalization_35[0][0]
                                                                    ']

 dense_53 (Dense)            (None, 184)                  34040     ['dropout_17[0][0]']

 batch_normalization_36 (Ba  (None, 184)                  736       ['dense_53[0][0]']
 tchNormalization)

 dense_54 (Dense)            (None, 184)                  36248     ['activation_17[0][0]']

 add_17 (Add)                (None, 184)                  0         ['batch_normalization_36[0][0]
                                                                    ',
                                                                     'dense_54[0][0]']

 activation_18 (Activation)  (None, 184)                  0         ['add_17[0][0]']

 dense_55 (Dense)            (None, 183)                  33855     ['activation_18[0][0]']

 batch_normalization_37 (Ba  (None, 183)                  732       ['dense_55[0][0]']
 tchNormalization)

 dropout_18 (Dropout)        (None, 183)                  0         ['batch_normalization_37[0][0]
                                                                    ']

 dense_56 (Dense)            (None, 183)                  33672     ['dropout_18[0][0]']

 batch_normalization_38 (Ba  (None, 183)                  732       ['dense_56[0][0]']
 tchNormalization)

 dense_57 (Dense)            (None, 183)                  33855     ['activation_18[0][0]']

 add_18 (Add)                (None, 183)                  0         ['batch_normalization_38[0][0]
                                                                    ',
                                                                     'dense_57[0][0]']

 activation_19 (Activation)  (None, 183)                  0         ['add_18[0][0]']

 dropout_19 (Dropout)        (None, 183)                  0         ['activation_19[0][0]']

 dense_58 (Dense)            (None, 1)                    184       ['dropout_19[0][0]']

==================================================================================================
Total params: 2093072 (7.98 MB)
Trainable params: 2078316 (7.93 MB)
Non-trainable params: 14756 (57.64 KB)
__________________________________________________________________________________________________
None
Epoch 1/200

[I 2026-03-20 08:23:29,727] Trial 31 finished with value: 0.25 and parameters: {'activation': 'relu6', 'regularizer_value_2': 7.5555797738899e-07, 'N_layers': 19, 'learning_rate': 0.0008875198749709292, 'optimizer': 'adam', 'N_1st_layer': 204, 'Dropout': 'y', 'N_1_layer': 222, 'Dropout_value_L2': 0.12082661650219075, 'N_2_layer': 201, 'Dropout_value_L3': 0.13541306402056852, 'N_3_layer': 165, 'Dropout_value_L4': 0.11025941339921728, 'N_4_layer': 202, 'Dropout_value_L5': 0.13249161593551412, 'N_5_layer': 241, 'Dropout_value_L6': 0.11493593998187408, 'N_6_layer': 181, 'Dropout_value_L7': 0.1391551474659517, 'N_7_layer': 151, 'Dropout_value_L8': 0.12214668171373465, 'N_8_layer': 202, 'Dropout_value_L9': 0.10083841941810988, 'N_9_layer': 223, 'Dropout_value_L10': 0.10214045059227451, 'N_10_layer': 164, 'Dropout_value_L11': 0.12679858360490984, 'N_11_layer': 192, 'Dropout_value_L12': 0.14252569195370632, 'N_12_layer': 158, 'Dropout_value_L13': 0.12649189807415018, 'N_13_layer': 167, 'Dropout_value_L14': 0.10048524499756332, 'N_14_layer': 222, 'Dropout_value_L15': 0.10729977236356499, 'N_15_layer': 166, 'Dropout_value_L16': 0.12749683441506504, 'N_16_layer': 167, 'Dropout_value_L17': 0.12197707936886915, 'N_17_layer': 196, 'Dropout_value_L18': 0.12042590173585345, 'N_18_layer': 184, 'Dropout_value_L19': 0.14222575981262073, 'N_19_layer': 183, 'Dropout_value_L20': 0.14242766694363546}. Best is trial 6 with value: 0.0.

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                Output Shape                 Param #   Connected to
==================================================================================================
 input_1 (InputLayer)        [(None, 12)]                 0         []

 dense (Dense)               (None, 162)                  2106      ['input_1[0][0]']

 activation (Activation)     (None, 162)                  0         ['dense[0][0]']

 batch_normalization (Batch  (None, 162)                  648       ['activation[0][0]']
 Normalization)

 dense_1 (Dense)             (None, 162)                  26406     ['batch_normalization[0][0]']

 batch_normalization_1 (Bat  (None, 162)                  648       ['dense_1[0][0]']
 chNormalization)

 dense_2 (Dense)             (None, 162)                  26406     ['batch_normalization_1[0][0]'
                                                                    ]

 batch_normalization_2 (Bat  (None, 162)                  648       ['dense_2[0][0]']
 chNormalization)

 dense_3 (Dense)             (None, 162)                  26406     ['batch_normalization[0][0]']

 add (Add)                   (None, 162)                  0         ['batch_normalization_2[0][0]'
                                                                    , 'dense_3[0][0]']

 activation_1 (Activation)   (None, 162)                  0         ['add[0][0]']

 dense_4 (Dense)             (None, 145)                  23635     ['activation_1[0][0]']

 batch_normalization_3 (Bat  (None, 145)                  580       ['dense_4[0][0]']
 chNormalization)

 dense_5 (Dense)             (None, 145)                  21170     ['batch_normalization_3[0][0]'
                                                                    ]

 batch_normalization_4 (Bat  (None, 145)                  580       ['dense_5[0][0]']
 chNormalization)

 dense_6 (Dense)             (None, 145)                  23635     ['activation_1[0][0]']

 add_1 (Add)                 (None, 145)                  0         ['batch_normalization_4[0][0]'
                                                                    , 'dense_6[0][0]']

 activation_2 (Activation)   (None, 145)                  0         ['add_1[0][0]']

 dense_7 (Dense)             (None, 243)                  35478     ['activation_2[0][0]']

 batch_normalization_5 (Bat  (None, 243)                  972       ['dense_7[0][0]']
 chNormalization)

 dense_8 (Dense)             (None, 243)                  59292     ['batch_normalization_5[0][0]'
                                                                    ]

 batch_normalization_6 (Bat  (None, 243)                  972       ['dense_8[0][0]']
 chNormalization)

 dense_9 (Dense)             (None, 243)                  35478     ['activation_2[0][0]']

 add_2 (Add)                 (None, 243)                  0         ['batch_normalization_6[0][0]'
                                                                    , 'dense_9[0][0]']

 activation_3 (Activation)   (None, 243)                  0         ['add_2[0][0]']

 dense_10 (Dense)            (None, 138)                  33672     ['activation_3[0][0]']

 batch_normalization_7 (Bat  (None, 138)                  552       ['dense_10[0][0]']
 chNormalization)

 dense_11 (Dense)            (None, 138)                  19182     ['batch_normalization_7[0][0]'
                                                                    ]

 batch_normalization_8 (Bat  (None, 138)                  552       ['dense_11[0][0]']
 chNormalization)

 dense_12 (Dense)            (None, 138)                  33672     ['activation_3[0][0]']

 add_3 (Add)                 (None, 138)                  0         ['batch_normalization_8[0][0]'
                                                                    , 'dense_12[0][0]']

 activation_4 (Activation)   (None, 138)                  0         ['add_3[0][0]']

 dense_13 (Dense)            (None, 186)                  25854     ['activation_4[0][0]']

 batch_normalization_9 (Bat  (None, 186)                  744       ['dense_13[0][0]']
 chNormalization)

 dense_14 (Dense)            (None, 186)                  34782     ['batch_normalization_9[0][0]'
                                                                    ]

 batch_normalization_10 (Ba  (None, 186)                  744       ['dense_14[0][0]']
 tchNormalization)

 dense_15 (Dense)            (None, 186)                  25854     ['activation_4[0][0]']

 add_4 (Add)                 (None, 186)                  0         ['batch_normalization_10[0][0]
                                                                    ',
                                                                     'dense_15[0][0]']

 activation_5 (Activation)   (None, 186)                  0         ['add_4[0][0]']

 dense_16 (Dense)            (None, 218)                  40766     ['activation_5[0][0]']

 batch_normalization_11 (Ba  (None, 218)                  872       ['dense_16[0][0]']
 tchNormalization)

 dense_17 (Dense)            (None, 218)                  47742     ['batch_normalization_11[0][0]
                                                                    ']

 batch_normalization_12 (Ba  (None, 218)                  872       ['dense_17[0][0]']
 tchNormalization)

 dense_18 (Dense)            (None, 218)                  40766     ['activation_5[0][0]']

 add_5 (Add)                 (None, 218)                  0         ['batch_normalization_12[0][0]
                                                                    ',
                                                                     'dense_18[0][0]']

 activation_6 (Activation)   (None, 218)                  0         ['add_5[0][0]']

 dense_19 (Dense)            (None, 209)                  45771     ['activation_6[0][0]']

 batch_normalization_13 (Ba  (None, 209)                  836       ['dense_19[0][0]']
 tchNormalization)

 dense_20 (Dense)            (None, 209)                  43890     ['batch_normalization_13[0][0]
                                                                    ']

 batch_normalization_14 (Ba  (None, 209)                  836       ['dense_20[0][0]']
 tchNormalization)

 dense_21 (Dense)            (None, 209)                  45771     ['activation_6[0][0]']

 add_6 (Add)                 (None, 209)                  0         ['batch_normalization_14[0][0]
                                                                    ',
                                                                     'dense_21[0][0]']

 activation_7 (Activation)   (None, 209)                  0         ['add_6[0][0]']

 dense_22 (Dense)            (None, 250)                  52500     ['activation_7[0][0]']

 batch_normalization_15 (Ba  (None, 250)                  1000      ['dense_22[0][0]']
 tchNormalization)

 dense_23 (Dense)            (None, 250)                  62750     ['batch_normalization_15[0][0]
                                                                    ']

 batch_normalization_16 (Ba  (None, 250)                  1000      ['dense_23[0][0]']
 tchNormalization)

 dense_24 (Dense)            (None, 250)                  52500     ['activation_7[0][0]']

 add_7 (Add)                 (None, 250)                  0         ['batch_normalization_16[0][0]
                                                                    ',
                                                                     'dense_24[0][0]']

 activation_8 (Activation)   (None, 250)                  0         ['add_7[0][0]']

 dense_25 (Dense)            (None, 189)                  47439     ['activation_8[0][0]']

 batch_normalization_17 (Ba  (None, 189)                  756       ['dense_25[0][0]']
 tchNormalization)

 dense_26 (Dense)            (None, 189)                  35910     ['batch_normalization_17[0][0]
                                                                    ']

 batch_normalization_18 (Ba  (None, 189)                  756       ['dense_26[0][0]']
 tchNormalization)

 dense_27 (Dense)            (None, 189)                  47439     ['activation_8[0][0]']

 add_8 (Add)                 (None, 189)                  0         ['batch_normalization_18[0][0]
                                                                    ',
                                                                     'dense_27[0][0]']

 activation_9 (Activation)   (None, 189)                  0         ['add_8[0][0]']

 dense_28 (Dense)            (None, 237)                  45030     ['activation_9[0][0]']

 batch_normalization_19 (Ba  (None, 237)                  948       ['dense_28[0][0]']
 tchNormalization)

 dense_29 (Dense)            (None, 237)                  56406     ['batch_normalization_19[0][0]
                                                                    ']

 batch_normalization_20 (Ba  (None, 237)                  948       ['dense_29[0][0]']
 tchNormalization)

 dense_30 (Dense)            (None, 237)                  45030     ['activation_9[0][0]']

 add_9 (Add)                 (None, 237)                  0         ['batch_normalization_20[0][0]
                                                                    ',
                                                                     'dense_30[0][0]']

 activation_10 (Activation)  (None, 237)                  0         ['add_9[0][0]']

 dense_31 (Dense)            (None, 167)                  39746     ['activation_10[0][0]']

 batch_normalization_21 (Ba  (None, 167)                  668       ['dense_31[0][0]']
 tchNormalization)

 dense_32 (Dense)            (None, 167)                  28056     ['batch_normalization_21[0][0]
                                                                    ']

 batch_normalization_22 (Ba  (None, 167)                  668       ['dense_32[0][0]']
 tchNormalization)

 dense_33 (Dense)            (None, 167)                  39746     ['activation_10[0][0]']

 add_10 (Add)                (None, 167)                  0         ['batch_normalization_22[0][0]
                                                                    ',
                                                                     'dense_33[0][0]']

 activation_11 (Activation)  (None, 167)                  0         ['add_10[0][0]']

 dense_34 (Dense)            (None, 170)                  28560     ['activation_11[0][0]']

 batch_normalization_23 (Ba  (None, 170)                  680       ['dense_34[0][0]']
 tchNormalization)

 dense_35 (Dense)            (None, 170)                  29070     ['batch_normalization_23[0][0]
                                                                    ']

 batch_normalization_24 (Ba  (None, 170)                  680       ['dense_35[0][0]']
 tchNormalization)

 dense_36 (Dense)            (None, 170)                  28560     ['activation_11[0][0]']

 add_11 (Add)                (None, 170)                  0         ['batch_normalization_24[0][0]
                                                                    ',
                                                                     'dense_36[0][0]']

 activation_12 (Activation)  (None, 170)                  0         ['add_11[0][0]']

 dense_37 (Dense)            (None, 211)                  36081     ['activation_12[0][0]']

 batch_normalization_25 (Ba  (None, 211)                  844       ['dense_37[0][0]']
 tchNormalization)

 dense_38 (Dense)            (None, 211)                  44732     ['batch_normalization_25[0][0]
                                                                    ']

 batch_normalization_26 (Ba  (None, 211)                  844       ['dense_38[0][0]']
 tchNormalization)

 dense_39 (Dense)            (None, 211)                  36081     ['activation_12[0][0]']

 add_12 (Add)                (None, 211)                  0         ['batch_normalization_26[0][0]
                                                                    ',
                                                                     'dense_39[0][0]']

 activation_13 (Activation)  (None, 211)                  0         ['add_12[0][0]']

 dense_40 (Dense)            (None, 242)                  51304     ['activation_13[0][0]']

 batch_normalization_27 (Ba  (None, 242)                  968       ['dense_40[0][0]']
 tchNormalization)

 dense_41 (Dense)            (None, 242)                  58806     ['batch_normalization_27[0][0]
                                                                    ']

 batch_normalization_28 (Ba  (None, 242)                  968       ['dense_41[0][0]']
 tchNormalization)

 dense_42 (Dense)            (None, 242)                  51304     ['activation_13[0][0]']

 add_13 (Add)                (None, 242)                  0         ['batch_normalization_28[0][0]
                                                                    ',
                                                                     'dense_42[0][0]']

 activation_14 (Activation)  (None, 242)                  0         ['add_13[0][0]']

 dense_43 (Dense)            (None, 152)                  36936     ['activation_14[0][0]']

 batch_normalization_29 (Ba  (None, 152)                  608       ['dense_43[0][0]']
 tchNormalization)

 dense_44 (Dense)            (None, 152)                  23256     ['batch_normalization_29[0][0]
                                                                    ']

 batch_normalization_30 (Ba  (None, 152)                  608       ['dense_44[0][0]']
 tchNormalization)

 dense_45 (Dense)            (None, 152)                  36936     ['activation_14[0][0]']

 add_14 (Add)                (None, 152)                  0         ['batch_normalization_30[0][0]
                                                                    ',
                                                                     'dense_45[0][0]']

 activation_15 (Activation)  (None, 152)                  0         ['add_14[0][0]']

 dense_46 (Dense)            (None, 140)                  21420     ['activation_15[0][0]']

 batch_normalization_31 (Ba  (None, 140)                  560       ['dense_46[0][0]']
 tchNormalization)

 dense_47 (Dense)            (None, 140)                  19740     ['batch_normalization_31[0][0]
                                                                    ']

 batch_normalization_32 (Ba  (None, 140)                  560       ['dense_47[0][0]']
 tchNormalization)

 dense_48 (Dense)            (None, 140)                  21420     ['activation_15[0][0]']

 add_15 (Add)                (None, 140)                  0         ['batch_normalization_32[0][0]
                                                                    ',
                                                                     'dense_48[0][0]']

 activation_16 (Activation)  (None, 140)                  0         ['add_15[0][0]']

 dropout (Dropout)           (None, 140)                  0         ['activation_16[0][0]']

 dense_49 (Dense)            (None, 1)                    141       ['dropout[0][0]']

==================================================================================================
Total params: 1819753 (6.94 MB)
Trainable params: 1807193 (6.89 MB)
Non-trainable params: 12560 (49.06 KB)
__________________________________________________________________________________________________
None
Epoch 1/200

In [ ]:
activation = "leaky_relu"
units1 = 177
units_per_1ayer = [197,187,195,187,131,177,128,150,173,160,197,169,155,204,188,204,160,175]
dropout = [0.11837708483323324,0.13737877910840118,0.1079956248790474,0.12698261124271906,0.12794531424007843,
           0.1296820415321237,0.133612397529674,0.12228020647719044,0.12220554795841516,0.12719421422552665,
           0.1442505597555257,0.10793263719860888,0.1320798929391686,0.10965275854307108,0.12948876012414212,
           0.10954741712920828,0.10762257284228328,0.1000578011775019]

r2 = 0.00000091842508974001
eta = 0.0008179841002734692

tf.keras.backend.clear_session()
inputs = layers.Input(shape = (X_train.shape[1],))
x = layers.Dense(units1, input_shape = (X_train.shape[1],))(inputs)
x = layers.Activation(activation)(x)
x = layers.BatchNormalization()(x)

for i in range(len(units_per_1ayer)):
    n = units_per_1ayer[i]
    # dropout_rate = 0
    dropout_rate = dropout[i]
    x = residual_block(x, n, activation, "t", dropout_rate, "L2", r2)            
            
x = layers.Dropout(0.4)(x)  
outputs = layers.Dense(1, activation = "sigmoid")(x)
model = models.Model(inputs, outputs)

model.compile(optimizer = tf.keras.optimizers.RMSprop(learning_rate = eta),
              loss = "binary_crossentropy",
              metrics = ["accuracy",
                         tf.keras.metrics.Precision(),
                         tf.keras.metrics.AUC(curve = "ROC"),
                         tf.keras.metrics.AUC(curve = "PR")])

wandb.init(project = "Residual-SnB(Balanced)-Trials-1.0",
           name = "Trial_1",
           reinit = True,
           config = {
               "Units_1": units1,
               "Units_per_layer": units_per_1ayer,
               "Droput": "yes",
               "Dropout_per_layer": dropout,
               "activation": activation,
               "n_layers": len(units_per_1ayer),
               "regularizer": "R2",
               "r_value2": r2,
               "learning_rate": eta,
               "optimizer": "Adam"})

print(model.summary())

early_stopping = EarlyStopping(monitor = "val_accuracy", patience = 7, restore_best_weights = True)
lr_reduction = ReduceLROnPlateau(monitor = "val_loss", factor = 0.1, patience = 5)

history = model.fit(X_train, y_train,
                    validation_data = (X_test, y_test),
                    batch_size = 32,
                    epochs = 200,
                    verbose = 1, 
                    callbacks = [WandbMetricsLogger(log_freq = 5), early_stopping, lr_reduction]
                   )

val_loss = min(history.history["val_loss"])
val_accuracy = max(history.history["val_accuracy"])
        
train_loss = min(history.history["loss"])
train_accuracy = max(history.history["accuracy"])

tf.keras.backend.clear_session()
gc.collect()
wandb.finish()

In [ ]:
model.save("ResNet-SnB-Higgs_B-Classificator-Balanced3.keras")

In [ ]:
model_ev = keras.models.load_model("ResNet-SnB-Higgs_B-Classificator-Balanced3.keras")

loss, accuracy, precision, auc, auc_1 = model_ev.evaluate(X_val, y_val, verbose = 1)

print(f"Test Loss: {loss:}")
print(f"Test Accuracy: {accuracy:}")

In [ ]:
from sklearn.metrics import confusion_matrix

y_pred = model_ev.predict(X_val)
y_pred_classes = (y_pred > 0.5).astype("int32")

cm = confusion_matrix(y_pred_classes, y_val)
sns.heatmap(cm, annot = True, fmt = "d", cmap = "rocket")

plt.xlabel("Prediction")
plt.ylabel("Real Value")
plt.show()